### ISSUE TITLE
How do I check FTP Connection Periodically?

### ISSUE THREAD

**Issue by wlsqkr2** [robinrodricks/FluentFTP#912] opened 2022-08-11 03:45 UTC
**FTP OS:** Unix

**FTP Server:** Vsftpd

**Computer OS:** Windows 10

**FluentFTP Version:** 39.2.1

**Framework:** .NET 4.5

How do I check FTP Connection Periodically?

I've already ftp connection, I'd like to check whether the server alive or not

Am I correct to use task.run() and AutoDectect() method?

**Comment by robinrodricks** [comment] 2022-08-11 06:05
Many ways : Noop, Connect/Disconnect. This is a usage question and not a bug/feature with the library so I'm closing it.

**Closed** 2022-08-11 06:06 UTC
Labels: question, faq
