### ISSUE TITLE
UploadFile error when destination folder is empty

### ISSUE THREAD

**Issue by olivierSOW** [robinrodricks/FluentFTP#315] opened 2018-07-13 14:24 UTC
**FTP OS:** Unix

**FTP Server:** ftpd

**Computer OS:** Raspberry 3+

Cannot upload file via uploadFile when destination folder is empty (no file present before uploading)
The command "NLST" get "550 No files found." response and then throw an exception

**Code:**
```
m_ftpClient = new FluentFTP.FtpClient(m_initStruct.host, m_initStruct.username, m_initStruct.password);
m_ftpClient.Encoding = System.Text.Encoding.UTF8; //need to accent in name even if server return it not reconize option
m_ftpClient.ListingParser = FluentFTP.FtpParser.Legacy; //trying without, same issue
m_ftpClient.Connect();

if(m_ftpClient.FileExists(destinationPath)) { /* destinationPath=usb/key1/seexport/2018-07-05_16-33-55 Les chats sont-ils les rois d'Internet_-Les félins insoumis/S1_/16-34-11_Micro 01_HC.mp3 */
	m_ftpClient.DeleteFile(destinationPath);
}
else { 
	//force create parent folder because reateRemoteDirectory parameter crash
	m_ftpClient.CreateDirectory(
		GetParentPath(destinationPath)
	);
}
	m_ftpClient.UploadFile(
		sourcePath /* sourcePath=d:\temp\seexport\temp\20180705_(PRIVATE)Les chats sont-ils les rois d'Internet__20180713_152928.0594\S1_\16-34-11_Micro 01_HC.mp3 */
		, destinationPath
		, FluentFTP.FtpExists.Overwrite //tried with differents options, same issue
		, false //createRemoteDirectory crash
		,FluentFTP.FtpVerify.None //tried with differents options, same issue
);
```

**Logs :**
# Connect()

> Status:   Connecting to 192.168.251.251:21
> Response: 220 seraspi FTP server (Version 6.4/OpenBSD/Linux-ftpd-0.17) ready.
> Command:  USER copycat
> Response: 331 Password required for copycat.
> Command:  PASS ***
> Response: 230 User copycat logged in.
> Response: 230-
> Response: 230- The programs included with the Debian GNU/Linux system are free software;
> Response: 230- the exact distribution terms for each program are described in the
> Response: 230- individual files in /usr/share/doc/*/copyright.
> Response: 230-
> Response: 230- Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
> Response: 230- permitted by applicable law.
> Command:  FEAT
> Response: 500 'FEAT': command not understood.
> Status:   Text encoding: System.Text.UTF8Encoding
> Command:  OPTS UTF8 ON
> Response: 500 'OPTS UTF8 ON': command not understood.
> Command:  SYST
> Response: 215 UNIX Type: L8 (Linux)
> Status:   Auto-detected UNIX listing parser

> # DirectoryExists("usb/key1/seexport/2018-07-05_16-33-55 Les chats sont-ils les rois d'Internet_-Les félins insoumis/S1_")
> 
> # GetWorkingDirectory()
> Command:  PWD
> Response: 257 "/home/copycat" is current directory.
> Command:  CWD usb/key1/seexport/2018-07-05_16-33-55 Les chats sont-ils les rois d'Internet_-Les félins insoumis/S1_
> Response: 550 usb/key1/seexport/2018-07-05_16-33-55 Les chats sont-ils les rois d'Internet_-Les félins insoumis/S1_: No such file or directory.
> 
> # DirectoryExists("usb/key1/seexport/2018-07-05_16-33-55 Les chats sont-ils les rois d'Internet_-Les félins insoumis")
> 
> # GetWorkingDirectory()
> Command:  PWD
> Response: 257 "/home/copycat" is current directory.
> Command:  CWD usb/key1/seexport/2018-07-05_16-33-55 Les chats sont-ils les rois d'Internet_-Les félins insoumis
> Response: 550 usb/key1/seexport/2018-07-05_16-33-55 Les chats sont-ils les rois d'Internet_-Les félins insoumis: No such file or directory.
> 
> # DirectoryExists("usb/key1/seexport")
> 
> # GetWorkingDirectory()
> Command:  PWD
> Response: 257 "/home/copycat" is current directory.
> Command:  CWD usb/key1/seexport
> Response: 550 usb/key1/seexport: No such file or directory.
> 
> # DirectoryExists("usb/key1")
> 
> # GetWorkingDirectory()
> Command:  PWD
> Response: 257 "/home/copycat" is current directory.
> Command:  CWD usb/key1
> Response: 250 CWD command successful.
> Command:  CWD /home/copycat
> Response: 250 CWD command successful.
> 
> # CreateDirectory("usb/key1/seexport", True)
> 
> # DirectoryExists("usb/key1")
> 
> # GetWorkingDirectory()
> Command:  PWD
> Response: 257 "/home/copycat" is current directory.
> Command:  CWD usb/key1
> Response: 250 CWD command successful.
> Command:  CWD /home/copycat
> Response: 250 CWD command successful.
> 
> # DirectoryExists("usb/key1/seexport")
> 
> # GetWorkingDirectory()
> Command:  PWD
> Response: 257 "/home/copycat" is current directory.
> Command:  CWD usb/key1/seexport
> Response: 550 usb/key1/seexport: No such file or directory.
> Status:   CreateDirectory usb/key1/seexport
> Command:  MKD usb/key1/seexport
> Response: 257 "usb/key1/seexport" directory created.
> 
> # CreateDirectory("usb/key1/seexport/2018-07-05_16-33-55 Les chats sont-ils les rois d'Internet_-Les félins insoumis", True)
> 
> # DirectoryExists("usb/key1/seexport")
> 
> # GetWorkingDirectory()
> Command:  PWD
> Response: 257 "/home/copycat" is current directory.
> Command:  CWD usb/key1/seexport
> Response: 250 CWD command successful.
> Command:  CWD /home/copycat
> Response: 250 CWD command successful.
> 
> # DirectoryExists("usb/key1/seexport/2018-07-05_16-33-55 Les chats sont-ils les rois d'Internet_-Les félins insoumis")
> 
> # GetWorkingDirectory()
> Command:  PWD
> Response: 257 "/home/copycat" is current directory.
> Command:  CWD usb/key1/seexport/2018-07-05_16-33-55 Les chats sont-ils les rois d'Internet_-Les félins insoumis
> Response: 550 usb/key1/seexport/2018-07-05_16-33-55 Les chats sont-ils les rois d'Internet_-Les félins insoumis: No such file or directory.
> Status:   CreateDirectory usb/key1/seexport/2018-07-05_16-33-55 Les chats sont-ils les rois d'Internet_-Les félins insoumis
> Command:  MKD usb/key1/seexport/2018-07-05_16-33-55 Les chats sont-ils les rois d'Internet_-Les félins insoumis
> Response: 257 "usb/key1/seexport/2018-07-05_16-33-55 Les chats sont-ils les rois d'Internet_-Les félins insoumis" directory created.
> 
> # CreateDirectory("usb/key1/seexport/2018-07-05_16-33-55 Les chats sont-ils les rois d'Internet_-Les félins insoumis/S1_", True)
> 
> # DirectoryExists("usb/key1/seexport/2018-07-05_16-33-55 Les chats sont-ils les rois d'Internet_-Les félins insoumis")
> 
> # GetWorkingDirectory()
> Command:  PWD
> Response: 257 "/home/copycat" is current directory.
> Command:  CWD usb/key1/seexport/2018-07-05_16-33-55 Les chats sont-ils les rois d'Internet_-Les félins insoumis
> Response: 250 CWD command successful.
> Command:  CWD /home/copycat
> Response: 250 CWD command successful.
> 
> # DirectoryExists("usb/key1/seexport/2018-07-05_16-33-55 Les chats sont-ils les rois d'Internet_-Les félins insoumis/S1_")
> 
> # GetWorkingDirectory()
> Command:  PWD
> Response: 257 "/home/copycat" is current directory.
> Command:  CWD usb/key1/seexport/2018-07-05_16-33-55 Les chats sont-ils les rois d'Internet_-Les félins insoumis/S1_
> Response: 550 usb/key1/seexport/2018-07-05_16-33-55 Les chats sont-ils les rois d'Internet_-Les félins insoumis/S1_: No such file or directory.
> Status:   CreateDirectory usb/key1/seexport/2018-07-05_16-33-55 Les chats sont-ils les rois d'Internet_-Les félins insoumis/S1_
> Command:  MKD usb/key1/seexport/2018-07-05_16-33-55 Les chats sont-ils les rois d'Internet_-Les félins insoumis/S1_
> Response: 257 "usb/key1/seexport/2018-07-05_16-33-55 Les chats sont-ils les rois d'Internet_-Les félins insoumis/S1_" directory created.
> SeexportClient.127.0.0.1_57916	INFO	copying file to usb/key1/seexport/2018-07-05_16-33-55 Les chats sont-ils les rois d'Internet_-Les félins insoumis/S1_/16-34-11_Micro 01_HC.mp3
> 
> # FileExists("usb/key1/seexport/2018-07-05_16-33-55 Les chats sont-ils les rois d'Internet_-Les félins insoumis/S1_/16-34-11_Micro 01_HC.mp3")
> 
> # GetWorkingDirectory()
> Command:  PWD
> Response: 257 "/home/copycat" is current directory.
> 
> # GetNameListing("/home/copycat/usb/key1/seexport/2018-07-05_16-33-55 Les chats sont-ils les rois d'Internet_-Les félins insoumis/S1_")
> Command:  TYPE I
> Response: 200 Type set to I.
> 
> # OpenPassiveDataStream(AutoPassive, "NLST /home/copycat/usb/key1/seexport/2018-07-05_16-33-55 Les chats sont-ils les rois d'Internet_-Les félins insoumis/S1_", 0)
> Command:  EPSV
> Response: 229 Extended Passive Mode OK (|||54671|)
> Status:   Connecting to 192.168.251.251:54671
> Command:  NLST /home/copycat/usb/key1/seexport/2018-07-05_16-33-55 Les chats sont-ils les rois d'Internet_-Les félins insoumis/S1_
> Response: 550 No files found.
> Status:   Disposing FtpSocketStream...
> 
> # CloseDataStream()
> Exception levée : 'FluentFTP.FtpCommandException' dans FluentFTP.dll
>

**Comment by olivierSOW** [comment] 2018-07-16 15:45
I do a fork with a workaround into LowLevel class. Certainly not the best solution:


`			if (!(reply = Execute(command)).Success) {
				if(command.StartsWith("NLST ") && reply.Code=="550" && reply.Message== "No files found.") {
					//workaround for ftpd which response "550 No files found" when folder exists but is empty
				}
				else {
					stream.Close();
					throw new FtpCommandException(reply);
				}
			}`

**Comment by Alexeyrnd** [comment] 2018-08-30 07:32
Same trouble. Problem solved?

**Comment by dendism** [comment] 2019-01-18 10:55
still not fixed in latest version (19.2.3).. UploadFile throws an exception if used with FtpExists.Overwrite or FtpExists.Skip and the destination directory is empty.. if there is any file, it works as expected

**Comment by olivierSOW** [comment] 2019-01-18 11:01
You can use my branch, i fix it but only for my way of use. I think i don’t fix it completly

 

 

 

De : dendism <notifications@github.com> 
Envoyé : vendredi 18 janvier 2019 11:56
À : robinrodricks/FluentFTP <FluentFTP@noreply.github.com>
Cc : olivierSOW <olivier.sow@alias.fr>; Author <author@noreply.github.com>
Objet : Re: [robinrodricks/FluentFTP] UploadFile error when destination folder is empty (#315)

 

still not fixed in latest version (19.2.3).. UploadFile throws an exception if used with FtpExists.Overwrite or FtpExists.Skip and the destination directory is empty.. if there is any file, it works as expected

**Comment by robinrodricks** [comment] 2019-02-27 06:26
Is this fixed in the latest release?

**Comment by robinrodricks** [comment] 2019-03-21 05:11
Please reply if you still have this issue.

**Closed by robinrodricks** 2019-03-21 05:11 UTC
Labels: fixed, possible bug

**Comment by dendism** [comment] 2019-03-21 07:33
i tried it with 2 different ftp servers - one was FileZilla ftp server - here it works like a charm. but the second one is proftpd (sadly used by the client) and there it is not working. here's more details about the server:

ProFTPD 1.2.10 Server
Command line to send FEAT
211-Features:
211-MDTM
211-REST STREAM
211-SIZE
211 End

dunno, if the problem is related to the proftpd or just bcoz it's a very old version. anyway as a workaround i just keep there empty text file :)
i can send you privately credentials, if you want to try it by yourself.

**Comment by olivierSOW** [comment] 2019-03-21 15:46
Sorry, i was busy.

Like as already said, i fix the error by myself. You can find the fix in my branch.

I didn’t try your new version at this time and have currently no time to do it.

 

Sorry

 

 




Olivier SOW
 <mailto:olivier.sow@alias.fr> olivier.sow@alias.fr 

	

251 avenue des Paluds
Z.I des Paluds BP1403
13785 AUBAGNE CEDEX
France 


Tel:

33 (0)4 42 700 545


Fax:

33 (0)4 42 700 546


e-mail:

 <mailto:alias@alias.fr> alias@alias.fr


web:

 <http://www.alias.fr/> http://www.alias.fr

 

 

 

De : Robinicks <notifications@github.com> 
Envoyé : jeudi 21 mars 2019 06:11
À : robinrodricks/FluentFTP <FluentFTP@noreply.github.com>
Cc : olivierSOW <olivier.sow@alias.fr>; Author <author@noreply.github.com>
Objet : Re: [robinrodricks/FluentFTP] UploadFile error when destination folder is empty (#315)

 

Please reply if you still have this issue.

**Comment by radian-jp** [comment] 2019-09-27 00:41
This bug may not be resolved.
If the destination directory is empty, it seems that an NLST command returns 550 and an exception occurs.
An exception does not occur if the destination directory is not empty.

FluentFTP: version 27.1.2 (net45)

Code:
    Sub Main()
        Try
            Using ftp As New FtpClient
                ftp.Host = "ServerIP"
                ftp.Port = 21
                ftp.Credentials = New Net.NetworkCredential("uid", "password")
                ftp.ConnectTimeout = 5000
                ftp.DataConnectionConnectTimeout = 5000
                ftp.DataConnectionReadTimeout = 5000
                ftp.ReadTimeout = 5000
                ftp.SocketKeepAlive = True
                ftp.DataConnectionType = FtpDataConnectionType.AutoPassive
                ftp.UploadDataType = FtpDataType.Binary
                ftp.Connect()
                Debug.WriteLine("ServerOS:" & ftp.ServerOS.ToString)
                Debug.WriteLine("ServerType:" & ftp.ServerType.ToString)
                ftp.UploadFile("C:\temp\test.xml", "./tmp/testdir/test.xml")
                Debug.WriteLine("upload success.")
            End Using

        Catch ex As Exception
            Debug.WriteLine("upload failed.")
            Debug.WriteLine(ex.ToString)
        End Try
    End Sub


Logs :
# Connect()
Status:   Connecting to [FTPServerIP]:21
Response: 220 [FTPServerName] FTP server ready.
Command:  USER cmfs
Response: 331 Password required for cmfs.
Command:  PASS ***
Response: 230 User cmfs logged in.
Command:  FEAT
Response: 500 'FEAT': command not understood.
Status:   Text encoding: System.Text.ASCIIEncoding
Command:  SYST
Response: 215 UNIX Type: L8 Version: SUNOS
ServerOS:Unix
ServerType:Unknown

# UploadFile("C:\temp\test.xml", "./tmp/testdir/test.xml", Overwrite, False, None)

# FileExists("./tmp/testdir/test.xml")

# GetWorkingDirectory()
Command:  PWD
Response: 257 "/export/home/cmfs" is current directory.

# GetNameListing("/export/home/cmfs/tmp/testdir")
Command:  TYPE I
Response: 200 Type set to I.

# OpenPassiveDataStream(AutoPassive, "NLST /export/home/cmfs/tmp/testdir", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||51775|)
Status:   Connecting to [FTPServerIP]:51775
Command:  NLST /export/home/cmfs/tmp/testdir
Response: 550 /export/home/cmfs/tmp/testdir/*: No such file or directory.
Status:   Disposing FtpSocketStream...

# CloseDataStream()
An exception was thrown: 'FluentFTP.FtpException' (FluentFTP.dll)

# Dispose()
Status:   Disposing FtpClient object...
Command:  QUIT
Response: 221-You have transferred 0 bytes in 0 files.
Response: 221-Total traffic for this session was 466 bytes in 0 transfers.
Response: 221-Thank you for using the FTP service on [FTPServerName].
Response: 221 Goodbye.
Status:   Disposing FtpSocketStream...
Status:   Disposing FtpSocketStream...
upload failed.
FluentFTP.FtpException: Error while uploading the file to the server. See InnerException for more info. ---> FluentFTP.FtpCommandException: /export/home/cmfs/tmp/testdir/*: No such file or directory.
   FluentFTP.FtpClient.OpenPassiveDataStream(FtpDataConnectionType type, String command, Int64 restart)
   FluentFTP.FtpClient.OpenDataStream(String command, Int64 restart)
   FluentFTP.FtpClient.GetNameListing(String path)
   FluentFTP.FtpClient.FileExists(String path)
   FluentFTP.FtpClient.UploadFileInternal(Stream fileData, String remotePath, Boolean createRemoteDir, FtpExists existsMode, Boolean fileExists, Boolean fileExistsKnown, IProgress`1 progress)
   --- End of InnerException stack trace ---
   FluentFTP.FtpClient.UploadFileInternal(Stream fileData, String remotePath, Boolean createRemoteDir, FtpExists existsMode, Boolean fileExists, Boolean fileExistsKnown, IProgress`1 progress)
   FluentFTP.FtpClient.UploadFileFromFile(String localPath, String remotePath, Boolean createRemoteDir, FtpExists existsMode, Boolean fileExists, Boolean fileExistsKnown, FtpVerify verifyOptions, IProgress`1 progress)
   FluentFTP.FtpClient.UploadFile(String localPath, String remotePath, FtpExists existsMode, Boolean createRemoteDir, FtpVerify verifyOptions, IProgress`1 progress)
   FluentFTPTest.Module1.Main() C:\munechika\vbnet-project\FluentFTPTest\FluentFTPTest\Module1.vb: 21
