### ISSUE TITLE
FXP source.TransferFile command > Progress update doesn't work

### ISSUE THREAD

**Issue by Joep81** [robinrodricks/FluentFTP#546] opened 2020-03-10 18:28 UTC
Hi,
I tried implementing the fairly new TransferFile API command. It works but i noticed that the progress tracking callback is not called.
For instance:
`client_src.UploadFile("e:\\ftp\\test.bin", ftpjobdest.filename, FtpRemoteExists.Overwrite, false, FtpVerify.OnlyChecksum, prog);` works but this

`client_src.TransferFile(ftpjobsrc.filename, client_dest, ftpjobdest.filename, false, FtpRemoteExists.Overwrite,FtpVerify.OnlyChecksum,  prog, metadata);`
is not.
The file is transferred correctly but the "prog" callback is not called.

Below my callback method
`Action<FtpProgress> prog = delegate (FtpProgress p)
                {
                    loggable.LogInfo(string.Format("Upload progress: {0}", p.Progress));                    
                };`
It would be nice if someone can fix this.

PS. I also tried the "TransferFileFXPInternal" API call but it gives the same problem.

What am i doing wrong here?
Thanks guys.

**Comment by robinrodricks** [comment] 2020-03-12 07:12
Will check and let you know.

**Comment by robinrodricks** [comment] 2020-03-16 09:11
TransferFileFXPInternal is an internal method and not to be used directly.

I can confirm that tracking progress for FXP transfers is not currently possible. We will work on it and get back to you.

**Comment by robinrodricks** [comment] 2020-03-16 09:14
@n0ix How can we support progress tracking even when `EnableThreadSafeDataConnections=false`? Because by default it is disabled as it causes performance and reliability issues. So we need to support this use case. Any ideas? Could we open a new FtpClient during the FXP Session and use it to track progress?

**Comment by n0ix** [comment] 2020-03-16 20:06
Yeah sure we could open a new session and report then the progress. This what we basically do if `EnableThreadSafeDataConnections `is set to `true`. Maybe i get this property wrong but doesen't it mean that only **one** session/connection is used? So it would be bad to use multiple connections to track progress even `EnableThreadSafeDataConnections ` is set to `false`.

Knowing that an ftp session/connection can only run one command at a time, I would say that it is not possible to control the FXP transfer and monitor the progress with one connection.

**Comment by robinrodricks** [comment] 2020-03-17 07:05
@Joep81  Please try this and see if it works.

[Release.zip](https://github.com/robinrodricks/FluentFTP/files/4341913/Release.zip)

#### 32.2.2
  - New: Tracking progress with FXP transfers is supported for all transfer modes
  - New: Track low-level progress with new `TransferredBytes` in `FtpProgress` class (thanks [Adhara3](/Adhara3))
  - New: `FXPProgressInterval` property to control how often FXP progress reports are sent
  - Fix: Hide `TransferFileFXPInternal` because its an internal transfer method and not to be used directly

**Comment by Joep81** [comment] 2020-03-17 09:47
@robinrodricks Yes that release works. I can see two connections being established to the destination ftp server. One for the file transfer and the other for regular SIZE updates. The command SIZE is send every second. I haven't had the chance to play with the "FXPProgressInterval" setting. Thanks for the quick fix.

**Comment by Joep81** [comment] 2020-03-17 10:06
@robinrodricks Short update from my side:
It looks that only the async version of the TransferFile is giving back progress updates. (TransferFileAsync) That is fine in my particular situation. Trying the TransferFile api command still gives no progress updates. 

I also tried to set FXPProgressInterval.
client_dest.FXPProgressInterval = 5000; That did not change the default one second interval to five seconds. I tried using this command on the destination client and the source ftp client. I also tried sending the command before and after the connection was established. No luck.

**Comment by robinrodricks** [comment] 2020-03-17 10:49
@n0ix I got progress tracking working. Just one thing. When we are cloning the target client connection, do you want to clone the working directory as well?

Then you need this:

     destinationClient.SetWorkingDirectory(remoteClient.GetWorkingDirectory());

Currently it is this which doesnt' make much sense:

    destinationClient.SetWorkingDirectory(destinationClient.GetWorkingDirectory());

**Comment by robinrodricks** [comment] 2020-03-17 10:54
@Joep81  Try now please. FXPProgressInterval should work.

[Release.zip](https://github.com/robinrodricks/FluentFTP/files/4343030/Release.zip)

**Comment by robinrodricks** [comment] 2020-03-17 11:13
Published - https://www.nuget.org/packages/FluentFTP/32.2.2


#### 32.2.2
  - New: Tracking progress with FXP transfers is supported for all transfer modes
  - New: Track low-level progress with new `TransferredBytes` in `FtpProgress` class (thanks [Adhara3](/Adhara3))
  - New: `FXPProgressInterval` property to control how often FXP progress reports are sent
  - Fix: Hide `TransferFileFXPInternal` because its an internal transfer method and not to be used directly

**Closed by robinrodricks** 2020-03-17 11:13 UTC
Labels: enhancement, work in progress
