### ISSUE TITLE
Process hang with GnuTLS on Linux/ARM64

### ISSUE THREAD

**Issue by dankaiadam** [robinrodricks/FluentFTP#1527] opened 2024-03-28 10:04 UTC
**FTP Server OS:** Windows

**FTP Server Type:** FileZilla Server 1.8.1

**Client Computer OS:** Debian/ARM64

**FluentFTP Version:** 49.0.2.0

**FluentFTP.GnuTLS Version:** 1.0.29.0

**Framework:** .NET 8

From my previous issue #1507 I experienced weird behavior when I tested connection interruption during file upload. Further looking into it, I saw that when this happens, the CPU usage jumps to 100% on one thread, and even the CancellationToken can't kill the process. 

**Logs :**

https://pastebin.com/QUBZFqZ5

I set the LogLevel to 10, that why I choose to share my log through pastebin. Around line 2720 is where I simulate connection interuption, and when the high CPU usage occurs.

**Comment by FanDjango** [comment] 2024-03-28 11:09
Thanks for supplying this. I see in the code where this is happening. I'll see what I can to to mitigate this.

**Comment by FanDjango** [comment] 2024-03-28 13:04
It turns out that to fully understand what is happening here, I must try to reproduce this **or** I could make a special branch of FluentFTP.GnuTLS for you, that you could use to produce such a log **again** with **even more** detail (sorry!). Do you think you can handle that?

One note: FluentFTP.GnuTLS runs sync and does not honor any cancellation token. So that is no wonder that it will loop and loop... but I would like to find out where and perhaps be able to prevent it.

**Comment by dankaiadam** [comment] 2024-03-28 13:20
Of course, let me know when you made the branch! 
With the even more detail, you mean a higher LogLevel?

**Comment by FanDjango** [comment] 2024-03-28 13:24
Same log level but some new diagnostic messages (temporary) in places where I need to see that is happening. Later today...

**Comment by FanDjango** [comment] 2024-03-28 22:16
So, this branch: https://github.com/FanDjango/FluentFTP.GnuTLS/tree/TestLoop
Use that instead of the NuGet.
There will be **huge** amounts of log.
Do a find on "STOR rock.xz" and delete all before that.
Then page forward until you can see the looping write with return -1, take many pages of that and put it in pastebin.
:-)

**Comment by FanDjango** [comment] 2024-03-29 19:32
Thanks, very helpful. I already fixed a few things, and will make a few more changes thanks to this log you sent.

Looks good now, right?

**Comment by FanDjango** [comment] 2024-03-29 19:49
I have merged the changes to FluentFTP.GnuTLS (current master) and will later cut a new Nuget release.

**Comment by dankaiadam** [comment] 2024-03-30 17:46
Yes looks great! I checked out the master branch as well just to be sure.
Little heads up, the verbose logs I think are hardcoded into the GnuTLS, because it shows up even with logging turned off.

**Closed** 2024-03-30 19:43 UTC
Labels: bug, fixed, filezilla-server
