### ISSUE TITLE
Error in DownloadDirectory with progress parameter

### ISSUE THREAD

**Issue by gjaba** [robinrodricks/FluentFTP#1518] opened 2024-03-27 08:18 UTC
**FTP Server OS:** Unix

**FTP Server Type:** cUrl

**Client Computer OS:** Windows 10

**FluentFTP Version:** 49.0.2

**Framework:** .NET 4.8

DownloadDirectory does not work with progress parameter. It works with the 49.0.1 version.
Here is my code sample:

```cs
var token = new CancellationToken();
using (var ftp = new AsyncFtpClient("ipv4Address", "usr", "pwd", logger: new SrsFtpLogger()))
{
    ftp.Config = new FtpConfig
    {
        EncryptionMode = FtpEncryptionMode.Auto,
        RetryAttempts = 5,
        SslProtocols = SslProtocols.None,
        ValidateAnyCertificate = true,
        DownloadDataType = FtpDataType.Binary
    };
    await ftp.Connect(token);
    var prog = new Progress<FluentFTP.FtpProgress>();
    await ftp.SetWorkingDirectory("/usr", token);
    await ftp.DownloadDirectory(@"dest", @"/usr", token: token,
        verifyOptions: FtpVerify.None, existsMode: FtpLocalExists.Overwrite, progress: prog);
}
```

**Logs :**

- With 49.0.1, It works with or without the progress parameter:
```
Command:  PASV
Waiting for response to: PASV
Response: 227 Entering Passive Mode (10,110,151,224,5,168) [5ms]
PASV advertised a non-routable IPAD. Using original connect dnsname/IPAD
Connecting to IP #1= ***:1448
Command:  RETR /usr/usrapp/kernel/userPage/type.pgx
Waiting for response to: RETR /usr/usrapp/kernel/userPage/type.pgx
Response: 150 Opening BINARY mode data connection [5ms]
Downloaded 766 bytes
Closing/Disposing FtpSocketStream(data connection)
Waiting for response to: RETR /usr/usrapp/kernel/userPage/type.pgx
Response: 226 Transfer complete [48ms]
         DownloadFile("E:\temp\testFtp\controller1\usrapp\kernel\userPage\typeCenter.pgx", "/usr/usrapp/kernel/userPage/typeCenter.pgx", Overwrite, None)
         GetFileSize("/usr/usrapp/kernel/userPage/typeCenter.pgx", -1)
         OpenRead("/usr/usrapp/kernel/userPage/typeCenter.pgx", Binary, 0, -1, False)
         OpenDataStreamAsync("RETR /usr/usrapp/kernel/userPage/typeCenter.pgx", 0)
         OpenPassiveDataStreamAsync(AutoPassive, "RETR /usr/usrapp/kernel/userPage/typeCenter.pgx", 0)
```

- With 49.0.2, it works only without the progress parameter. See below logs with the progress param:

```
Command:  PASV
Waiting for response to: PASV
Response: 227 Entering Passive Mode (10,110,151,224,7,150) [5ms]
PASV advertised a non-routable IPAD. Using original connect dnsname/IPAD
Connecting to IP #1= ***:1942
Command:  RETR /usr/temp/pdrv.sys
Waiting for response to: RETR /usr/temp/pdrv.sys
Response: 150 Opening BINARY mode data connection [20ms]
Closing/Disposing FtpSocketStream(data connection)
File failed to download: /usr/temp/pdrv.sys
>         DownloadFile("E:\temp\testFtp\controller1\applicom\io_pierre_save_17_10_2017\configTag.xml", "/usr/appl
>         GetFileSize("/usr/applicom/io_pierre_save_17_10_2017/configTag.xml", -1)
>         OpenRead("/usr/applicom/io_pierre_save_17_10_2017/configTag.xml", Binary, 0, -1, False)
>         OpenDataStreamAsync("RETR /usr/applicom/io_pierre_save_17_10_2017/configTag.xml", 0)
>         OpenPassiveDataStreamAsync(AutoPassive, "RETR /usr/applicom/io_pierre_save_17_10_2017/configTag.xml", 0
Command:  PASV
Waiting for response to: PASV
Response: 226 Transfer complete [3ms]
File failed to download: /usr/applicom/io_pierre_save_17_10_2017/configTag.xml
>         DownloadFile("E:\temp\testFtp\controller1\applicom\io_pierre_save_17_10_2017\applicomIO.ply", "/usr/app
>         GetFileSize("/usr/applicom/io_pierre_save_17_10_2017/applicomIO.ply", -1)
>         OpenRead("/usr/applicom/io_pierre_save_17_10_2017/applicomIO.ply", Binary, 0, -1, False)
>         OpenDataStreamAsync("RETR /usr/applicom/io_pierre_save_17_10_2017/applicomIO.ply", 0)
>         OpenPassiveDataStreamAsync(AutoPassive, "RETR /usr/applicom/io_pierre_save_17_10_2017/applicomIO.ply", 
Command:  PASV
Waiting for response to: PASV
Response: 227 Entering Passive Mode (10,110,151,224,7,151) [5ms]
PASV advertised a non-routable IPAD. Using original connect dnsname/IPAD
Connecting to IP #1= ***:1943
File failed to download: /usr/applicom/io_pierre_save_17_10_2017/applicomIO.ply
>         DownloadFile("E:\temp\testFtp\controller1\applicom\modbus\modbus.xml", "/usr/applicom/modbus/modbus.xml
>         GetFileSize("/usr/applicom/modbus/modbus.xml", -1)
>         OpenRead("/usr/applicom/modbus/modbus.xml", Binary, 0, -1, False)
>         OpenDataStreamAsync("RETR /usr/applicom/modbus/modbus.xml", 0)
>         OpenPassiveDataStreamAsync(AutoPassive, "RETR /usr/applicom/modbus/modbus.xml", 0)
Control connection has stale data - prior to command execution of "PASV"
The stale data was (length = 50):
Stale:    227 Entering Passive Mode (10,110,151,224,7,152)
Reconnect needed due to stale data present on control connection
Command stashed: PASV
Closing/Disposing FtpSocketStream(control connection)
>         Connect(True)
Reconnect (Count: 1)
FluentFTP 49.0.2.0(.NET Framework 4.7.2)
Connecting to IP #1= ***:21
Waiting for a response
Response: 220 VxWorks FTP server (VxWorks VxWorks5.5.1) ready. [2.262s]
Command:  AUTH TLS
Waiting for response to: AUTH TLS
Response: 530 USER and PASS required [4ms]
Command:  USER ***
Waiting for response to: USER ***
Response: 331 Password required [66ms]
Command:  PASS ***
Waiting for response to: PASS ***
Response: 230 User logged in [2ms]
Command:  FEAT
Waiting for response to: FEAT
Response: 500 Command not recognized [3ms]
Text encoding: System.Text.ASCIIEncoding
Command:  SYST
Waiting for response to: SYST
Response: 215 UNIX Type: L8 Version: VxWorks [4ms]
Active ServerHandler is: None
Listing parser set to: Unix
Command:  TYPE I
Waiting for response to: TYPE I
Response: 200 Type set to I, binary mode [3ms]
>         SetWorkingDirectory("/usr")
Command:  CWD /usr
Waiting for response to: CWD /usr
Response: 250 Changed directory to "/usr" [4ms]
Executing stashed command
Command:  PASV
Waiting for response to: PASV
Response: 227 Entering Passive Mode (10,110,151,224,7,153) [5ms]
PASV advertised a non-routable IPAD. Using original connect dnsname/IPAD
Connecting to IP #1= ***:1945
Command:  RETR /usr/applicom/modbus/modbus.xml
Waiting for response to: RETR /usr/applicom/modbus/modbus.xml
Response: 150 Opening BINARY mode data connection [21ms]
Closing/Disposing FtpSocketStream(data connection)
File failed to download: /usr/applicom/modbus/modbus.xml
>         DownloadFile("E:\temp\testFtp\controller1\applicom\io\config\ADMINMSG.041", "/usr/applicom/io/config/AD
>         GetFileSize("/usr/applicom/io/config/ADMINMSG.041", -1)
>         OpenRead("/usr/applicom/io/config/ADMINMSG.041", Binary, 0, -1, False)
>         OpenDataStreamAsync("RETR /usr/applicom/io/config/ADMINMSG.041", 0)
>         OpenPassiveDataStreamAsync(AutoPassive, "RETR /usr/applicom/io/config/ADMINMSG.041", 0)
Command:  EPSV
Waiting for response to: EPSV
Response: 226 Transfer complete [2ms]
File failed to download: /usr/applicom/io/config/ADMINMSG.041
>         DownloadFile("E:\temp\testFtp\controller1\applicom\io\config\ADMINMSG.042", "/usr/applicom/io/config/AD
>         GetFileSize("/usr/applicom/io/config/ADMINMSG.042", -1)
>         OpenRead("/usr/applicom/io/config/ADMINMSG.042", Binary, 0, -1, False)
>         OpenDataStreamAsync("RETR /usr/applicom/io/config/ADMINMSG.042", 0)
>         OpenPassiveDataStreamAsync(AutoPassive, "RETR /usr/applicom/io/config/ADMINMSG.042", 0)
Command:  EPSV
Waiting for response to: EPSV
Response: 500 Command not recognized [3ms]
>         OpenPassiveDataStreamAsync(PASV, "RETR /usr/applicom/io/config/ADMINMSG.042", 0)
Command:  PASV
Waiting for response to: PASV
Response: 500 Command not recognized [2ms]
File failed to download: /usr/applicom/io/config/ADMINMSG.042
>         DownloadFile("E:\temp\testFtp\controller1\applicom\io\config\ADMINMSG.043", "/usr/applicom/io/config/AD
>         GetFileSize("/usr/applicom/io/config/ADMINMSG.043", -1)
>         OpenRead("/usr/applicom/io/config/ADMINMSG.043", Binary, 0, -1, False)
>         OpenDataStreamAsync("RETR /usr/applicom/io/config/ADMINMSG.043", 0)
>         OpenPassiveDataStreamAsync(AutoPassive, "RETR /usr/applicom/io/config/ADMINMSG.043", 0)
Command:  PASV
Waiting for response to: PASV
Response: 227 Entering Passive Mode (10,110,151,224,7,154) [6ms]
PASV advertised a non-routable IPAD. Using original connect dnsname/IPAD
Connecting to IP #1= ***:1946
File failed to download: /usr/applicom/io/config/ADMINMSG.043
>         DownloadFile("E:\temp\testFtp\controller1\applicom\io\config\ADMINMSG.044", "/usr/applicom/io/config/AD
>         GetFileSize("/usr/applicom/io/config/ADMINMSG.044", -1)
>         OpenRead("/usr/applicom/io/config/ADMINMSG.044", Binary, 0, -1, False)
>         OpenDataStreamAsync("RETR /usr/applicom/io/config/ADMINMSG.044", 0)
>         OpenPassiveDataStreamAsync(AutoPassive, "RETR /usr/applicom/io/config/ADMINMSG.044", 0)
Control connection has stale data - prior to command execution of "PASV"
The stale data was (length = 50):
Stale:    227 Entering Passive Mode (10,110,151,224,7,155)
Reconnect needed due to stale data present on control connection
Command stashed: PASV
Closing/Disposing FtpSocketStream(control connection)
```

**Comment by FanDjango** [comment] 2024-03-27 13:36
Here is my code sample, _it works **with** progress:_ I tried it just now.

```cs
					Progress<FtpProgress> asyncprogress = new Progress<FtpProgress>(p => {
						Console.WriteLine(p.Progress.ToString() + "% complete");
						//Console.SetCursorPosition(0, Console.CursorTop - 1);
					});

					await client.Connect();

					await client.DownloadDirectory("D:\\testdir", "/home/mike/test", FtpFolderSyncMode.Update, FtpLocalExists.Overwrite, FtpVerify.None, progress: asyncprogress);

					await client.Disconnect();
```
So more analysis is necessary which means **more input** from your side.

In your log of the "does not work":

I think that "File failed to download" means that one of the files in the directory failed to download (not really, because later there is a "226 Transfer complete [3ms]") and that FluentFTP did not correctly react to that, it tried to continue with the next file without correct logic.

**Something is "fishy" about `/usr/temp/pdrv.sys`** and **we are not handling it correctly. The is no "Downloaded nnnn bytes", the transfer ends/fails and then we see the "226 Transfer complete" message.

**Comment by FanDjango** [comment] 2024-03-27 13:39
So, I don't think 

1. Progress causes the problem
2. Older FluentFTP work, new one doesn't: Well, it would certainly make your issue more credible if **both** logs were from trying to download the **same** set of files instead of different ones.

**Comment by FanDjango** [comment] 2024-03-27 13:49
There is some more strange stuff to be seen in that log:

1. Server does not support the FEAT command. Well, that's not a problem really, but it shows up that the server is somewhat strange.
2.  After the reconnect (which happens because we don't ever recover from the de-sync of commands and responses after the first failure) the download of **an other** files also fails. Strange...
3. And then suddenly using EPSV instead of PASV?

**Comment by FanDjango** [comment] 2024-03-27 13:55
It looks like there are a number of things that need to be investigated. Let's see how we can proceed on this.

Are you able to reproduce the problem for a static unchanging directory, and does the problem look the exactly the same each try?

**Comment by FanDjango** [comment] 2024-03-27 14:41
One more thing:

Here is my log:
```
>         DownloadFile("D:\testdir\vmlinuz-6.1.0-18-amd64", "/home/mike/test/vmlinuz-6.1.0-18-amd64", Overwrite, None)
>         GetFileSize("vmlinuz-6.1.0-18-amd64", -1)
Command:  SIZE vmlinuz-6.1.0-18-amd64
Status:   Waiting for response to: SIZE vmlinuz-6.1.0-18-amd64
Response: 213 8152768 [<1ms]
>         OpenRead("vmlinuz-6.1.0-18-amd64", Binary, 0, 8152768, False)
>         OpenDataStreamAsync("RETR vmlinuz-6.1.0-18-amd64", 0)
>         OpenPassiveDataStreamAsync(PASV, "RETR vmlinuz-6.1.0-18-amd64", 0)
Command:  PASV
Status:   Waiting for response to: PASV
Response: 227 Entering Passive Mode (192,168,1,109,181,249). [1ms]
```
Where are the SIZE commands in your logs? I can see the GetFileSize call line, but you have redacted?

**Comment by FanDjango** [comment] 2024-03-27 15:00
I think after studying this for a while, I have found out what might be going on:

It could be that the action called by the progress reporting is causing an exception. This exception is not reported, the download is ended prematurely because is catches this and then DownloadDirectory blithely continues for the next file (because it Try/Catches (and ignores), but the Command/Response Sequence ist not in sync anymore.

Something in **your** progress reporting must be different from mine.

I will continue testing this. It is a fascinating issue!

**Comment by FanDjango** [comment] 2024-03-27 16:36
Ok. I found your problem.

Let's make a long story short:

PR #1447 made a change in Up/Download that causes an exception in the Up/Download loop in a special case.

That caused:

**Problem #1**: Exceptions in the Up/Download loop are handled by higher level API routines in differing ways. In the case of DownloadDirectory, for example, the actual execption was well hidden and ignored, instead skipping to the next file. The failure was instead recorded in the produced file list.
**No message is produced, no indication that something went wrong** -> **BUG**

Due to-

**Problem #2**: In case of an execption in the Up/Download loop, it ends without at least trying to read any last messages from the server. These messages then remain **hanging** in the control connection and any retries or further actions go out of sync. -> **BUG**

And now, you encountered the PR #1447, which actually causes (in some cases) an error for the Up/Download loop, thereby incurring Problems #2 and also #1.

The final drop:

**Problem #3**: PR #1447 introduced a bug which will cause an exception if GetFileSize cannot determine the file size. There are a few cases where this can happen and your **server**, which has no FEAT command therefore does not support the SIZE command produces no filesize -> **BOOM**: All three problems now manifest. And of course - if no progress is requested, the code doesn't mind the missing file size, it isn't needed, no BOOM.

I have fixed #1, also #2 and committed that change to current master.

#3 has actually also already been fixed (by @andreasstolpmann (Kudos and thx! PR #1519) and has been already commited to master earlier this day.

So your problem should be solved by getting the current master.

**Comment by gjaba** [comment] 2024-03-28 07:07
Hello @FanDjango, thank you for your quick reply and your time !

**Comment by FanDjango** [comment] 2024-03-28 22:18
I have independant confirmation of this fix is working. So I am closing this.

**Closed** 2024-03-28 22:18 UTC
Labels: bug, fixed, cUrl-server
