### ISSUE TITLE
UploadFile returned with status Failed. File with 0 size created on server 

### ISSUE THREAD

**Issue by DrorSegev** [robinrodricks/FluentFTP#658] opened 2020-12-08 09:41 UTC
**FTP OS:** Unix 

**FTP Server: UNIX emulated by FileZilla

**Computer OS:Win10?

**FluentFTP Version:33.03 

Hi, 
File upload (UploadFile) returned with status Failed. File with 0 size created on server  
Connection is  client.EncryptionMode = FtpEncryptionMode.Implicit; (FTPS)
From the same computer I can upload the file when using winscp, so it is not a firewall issue.
Any help will be appreciated.
Tnx
Dror

**Logs :**

```
# Connect()
Status:   Connecting to ***:990
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.0230025.
Response: 220-Hello,
Response: 220-
Response: 220-Unauthorized access to this system is forbidden and will be prosecuted by A
Response: 220-
Response: 220-By accessing this system, you agree that your actions may be monitored.
Response: 220-
Response: 220-For your information - all activity on **************** is logged.
Response: 220-
Response: 220 !!!!!!!!!files older than 30 days will be deleted without further notice.!!
Command:  USER ***
Response: 331 Password required for ******
Command:  PASS ***
Response: 230 Logged on
Command:  PBSZ 0
Response: 200 PBSZ=0
Command:  PROT P
Response: 200 Protection level set to P
Command:  FEAT
Response: 211-Features:
Response: MDTM
Response: REST STREAM
Response: SIZE
Response: MLST type*;size*;modify*;
Response: MLSD
Response: AUTH SSL
Response: AUTH TLS
Response: PROT
Response: PBSZ
Response: UTF8
Response: CLNT
Response: MFMT
Response: EPSV
Response: EPRT
Response: 211 End
Status:   Text encoding: System.Text.UTF8Encoding
Command:  OPTS UTF8 ON
Response: 202 UTF8 mode is always enabled. No need to send this command.
Command:  SYST
Response: 215 UNIX emulated by FileZilla
Command:  SIZE /dor.pdf
Response: 213 0

# DeleteFile("/dor.pdf")
Command:  DELE /dor.pdf
Response: 250 File deleted successfully

# OpenWrite("/dor.pdf", Binary)
Command:  TYPE I
Response: 200 Type set to I

# OpenPassiveDataStream(AutoPassive, "STOR /dor.pdf", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||4000|)
Status:   Connecting to ***:4000
Command:  STOR /dor.pdf
Response: 150 Opening data channel for file upload to server of "/dor.pdf"
Status:   IOException for file c:\temp\140794.pdf : Authentication failed because the remote party has closed the transport stream.
Status:   Failed to upload file.
-->```

**Comment by robinrodricks** [comment] 2021-01-03 14:42
Its because your FTP server is blocking data connections that are opened to upload the file. ("Authentication failed because the remote party has closed the transport stream.")

You need to change the connection type, see [this for details](https://github.com/robinrodricks/FluentFTP/wiki/FTP-Connection#ftp-settings).

**Comment by novak-as** [comment] 2021-01-18 10:46
I can confirm the same behavior for the https://github.com/robinrodricks/FluentFTP/issues/668

**Comment by robinrodricks** [comment] 2021-02-10 14:41
Closing because seems to be server/authentication issue as described and not a bug with FluentFTP.

**Closed by robinrodricks** 2021-02-10 14:41 UTC
Labels: server specific, server-issue

**Comment by pmarangoni** [comment] 2021-05-26 21:54
I'm having this problem too.

My code:
`ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
using (FtpClient client = new FtpClient(ftp_address, ftp_port, ftp_un, ftp_pw))
{
    client.EncryptionMode = FtpEncryptionMode.Implicit;
    client.SslProtocols = SslProtocols.Tls12;
    client.DataConnectionType = FtpDataConnectionType.AutoPassive;
    client.ValidateCertificate += new FtpSslValidation(OnValidateCertificate);
    client.Connect();

    if (client.IsConnected)
    { 
        FtpStatus ftpStatus = client.UploadFile(filePath, ftp_filename, FtpRemoteExists.Overwrite, false, FtpVerify.None, null);
        if (ftpStatus == FtpStatus.Success)
        {
            // log upload
        }
        else
        {
            // log error
        }
        client.Disconnect();
    }
}
`
Log output:
```
# Connect()
Status:   Connecting to ***.***.***.***
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.1624838.
Response: 220 FileZilla Server 0.9.60 beta written by Tim Kosse (Tim.Kosse@gmx.de) Please visit http://sourceforge.
Status:   Detected FTP server: FileZilla
Command:  USER w64upload
'iisexpress.exe' (CLR v4.0.30319: /LM/W3SVC/2/ROOT-6-132665388072666717): Loaded 
Response: 331 Password required for remoteFtpServer
Command:  PASS ***
Response: 230 Logged on
Command:  PBSZ 0
Response: 200 PBSZ=0
Command:  PROT P
Response: 200 Protection level set to P
Command:  FEAT
Response: 211-Features:
Response: MDTM
Response: REST STREAM
Response: SIZE
Response: MLST type*;size*;modify*;
Response: MLSD
Response: AUTH SSL
Response: AUTH TLS
Response: PROT
Response: PBSZ
Response: UTF8
Response: CLNT
Response: MFMT
Response: EPSV
Response: EPRT
Response: 211 End
Status:   Text encoding: System.Text.UTF8Encoding
Command:  OPTS UTF8 ON
Response: 202 UTF8 mode is always enabled. No need to send this command.
Command:  SYST
Response: 215 UNIX emulated by FileZilla

# UploadFile("D:\Repos\filename.csv", "filename.csv", Overwrite, False, None)

# FileExists("filename.csv")

# GetWorkingDirectory()
Command:  PWD
Response: 257 "/" is current directory.
Command:  SIZE /filename.csv
Response: 550 File not found

# OpenWrite("filename.csv", Binary)
Command:  TYPE I
Response: 200 Type set to I

# OpenPassiveDataStream(AutoPassive, "STOR filename.csv", 0)
Command:  EPSV
Response: 229 Entering Extended Passive Mode (|||35003|)
Status:   Connecting to  ***.***.***.***:35003

Command:  STOR filename.csv

Response: 150 Opening data channel for file upload to server of "/filename0.csv"
Status:   IOException for file D:\Repos\filename.csv : Authentication failed because the remote party has closed the transport stream.
Status:   Failed to upload file.
Status:   There is stale data on the socket, maybe our connection timed out or you did not call GetReply(). Re-connecting...
Status:   Disposing FtpSocketStream...
Status:   Not sending QUIT because the connection has already been closed.
Status:   Disposing FtpSocketStream...

# Dispose()
Status:   Disposing FtpClient object...
Status:   Disposing FtpSocketStream...
The program '[7044] iisexpress.exe' has exited with code 0 (0x0).
```

**Comment by Mystogun** [comment] 2022-02-11 21:48
I'm having the same problem
But the logs don't tell me anything

Logs:

`
# AutoConnect()

# AutoDetect(True, False)

# Connect()
Status:   Connecting to ***:21
Response: 220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
Response: 220-You are user number 7 of 50 allowed.
Response: 220-Local time is now 22:47. Server port: 21.
Response: 220-IPv6 connections are also welcome on this server.
Response: 220 You will be disconnected after 15 minutes of inactivity.
Status:   Detected FTP server: PureFTPd
Command:  AUTH TLS
Response: 234 AUTH TLS OK.
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.2803308.
Command:  USER ***
Response: 331 User *** OK. Password required
Command:  PASS ***
Response: 230 OK. Current restricted directory is /
Command:  PBSZ 0
Response: 200 PBSZ=0
Command:  PROT P
Response: 200 Data protection level set to "private"
Command:  FEAT
Response: 211-Extensions supported:
Response: EPRT
Response: IDLE
Response: MDTM
Response: SIZE
Response: MFMT
Response: REST STREAM
Response: MLST type*;size*;sizd*;modify*;UNIX.mode*;UNIX.uid*;UNIX.gid*;unique*;
Response: MLSD
Response: AUTH TLS
Response: PBSZ
Response: PROT
Response: UTF8
Response: ESTA
Response: PASV
Response: EPSV
Response: SPSV
Response: ESTP
Response: 211 End.
Status:   Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
Command:  OPTS UTF8 ON
Response: 200 OK, UTF-8 enabled
Command:  SYST
Response: 215 UNIX Type: L8
Status:   Listing parser set to: Machine

# GetFilePermissions("/public_html")

# GetObjectInfo("/public_html", False)
Command:  MLST /public_html
Response: 250-Begin
Response: type=dir;sizd=4096;modify=20220211214012;UNIX.mode=0755;UNIX.uid=1003;UNIX.gid=99;unique=802gc42769; /public_html
Response: 250 End.

# UploadFile("RE2GpHd_1920x1080.jpg", "/public_html/RE2GpHd_1920x1080.jpg", Overwrite, False, None)

# FileExists("/public_html/RE2GpHd_1920x1080.jpg")
Command:  SIZE /public_html/RE2GpHd_1920x1080.jpg
Response: 213 0

# DeleteFile("/public_html/RE2GpHd_1920x1080.jpg")
Command:  DELE /public_html/RE2GpHd_1920x1080.jpg
Response: 250 Deleted /public_html/RE2GpHd_1920x1080.jpg

# OpenWrite("/public_html/RE2GpHd_1920x1080.jpg", Binary)

# GetFileSize("/public_html/RE2GpHd_1920x1080.jpg")
Command:  SIZE /public_html/RE2GpHd_1920x1080.jpg
Response: 550 Can't check for file existence
Command:  TYPE I
Response: 200 TYPE is now 8-bit binary

# OpenPassiveDataStream(PASV, "STOR /public_html/RE2GpHd_1920x1080.jpg", 0)
Command:  PASV
Response: 227 Entering Passive Mode (173,212,202,2,159,80)
Status:   Connecting to ***:40784
Command:  STOR /public_html/RE2GpHd_1920x1080.jpg
Response: 150 Accepted data connection
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.1919184.
Status:   Disposing FtpSocketStream...

# OpenAppend("/public_html/RE2GpHd_1920x1080.jpg", Binary)

# GetFileSize("/public_html/RE2GpHd_1920x1080.jpg")
Command:  SIZE /public_html/RE2GpHd_1920x1080.jpg

# OpenPassiveDataStream(PASV, "APPE /public_html/RE2GpHd_1920x1080.jpg", 0)
Command:  PASV
Status:   Disposing FtpSocketStream...
`

**Comment by Mystogun** [comment] 2022-02-11 21:52
Hi 

I also get a 0 size file on the server when using FileUpload, but the logs don't show me anything

Here are the logs:

```

# AutoConnect()

# AutoDetect(True, False)

# Connect()
Status:   Connecting to ***:21
Response: 220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
Response: 220-You are user number 7 of 50 allowed.
Response: 220-Local time is now 22:47. Server port: 21.
Response: 220-IPv6 connections are also welcome on this server.
Response: 220 You will be disconnected after 15 minutes of inactivity.
Status:   Detected FTP server: PureFTPd
Command:  AUTH TLS
Response: 234 AUTH TLS OK.
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.2803308.
Command:  USER ***
Response: 331 User *** OK. Password required
Command:  PASS ***
Response: 230 OK. Current restricted directory is /
Command:  PBSZ 0
Response: 200 PBSZ=0
Command:  PROT P
Response: 200 Data protection level set to "private"
Command:  FEAT
Response: 211-Extensions supported:
Response: EPRT
Response: IDLE
Response: MDTM
Response: SIZE
Response: MFMT
Response: REST STREAM
Response: MLST type*;size*;sizd*;modify*;UNIX.mode*;UNIX.uid*;UNIX.gid*;unique*;
Response: MLSD
Response: AUTH TLS
Response: PBSZ
Response: PROT
Response: UTF8
Response: ESTA
Response: PASV
Response: EPSV
Response: SPSV
Response: ESTP
Response: 211 End.
Status:   Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
Command:  OPTS UTF8 ON
Response: 200 OK, UTF-8 enabled
Command:  SYST
Response: 215 UNIX Type: L8
Status:   Listing parser set to: Machine

# GetFilePermissions("/public_html")

# GetObjectInfo("/public_html", False)
Command:  MLST /public_html
Response: 250-Begin
Response: type=dir;sizd=4096;modify=20220211214012;UNIX.mode=0755;UNIX.uid=1003;UNIX.gid=99;unique=802gc42769; /public_html
Response: 250 End.

# UploadFile("RE2GpHd_1920x1080.jpg", "/public_html/RE2GpHd_1920x1080.jpg", Overwrite, False, None)

# FileExists("/public_html/RE2GpHd_1920x1080.jpg")
Command:  SIZE /public_html/RE2GpHd_1920x1080.jpg
Response: 213 0

# DeleteFile("/public_html/RE2GpHd_1920x1080.jpg")
Command:  DELE /public_html/RE2GpHd_1920x1080.jpg
Response: 250 Deleted /public_html/RE2GpHd_1920x1080.jpg

# OpenWrite("/public_html/RE2GpHd_1920x1080.jpg", Binary)

# GetFileSize("/public_html/RE2GpHd_1920x1080.jpg")
Command:  SIZE /public_html/RE2GpHd_1920x1080.jpg
Response: 550 Can't check for file existence
Command:  TYPE I
Response: 200 TYPE is now 8-bit binary

# OpenPassiveDataStream(PASV, "STOR /public_html/RE2GpHd_1920x1080.jpg", 0)
Command:  PASV
Response: 227 Entering Passive Mode (173,212,202,2,159,80)
Status:   Connecting to ***:40784
Command:  STOR /public_html/RE2GpHd_1920x1080.jpg
Response: 150 Accepted data connection
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.1919184.
Status:   Disposing FtpSocketStream...

# OpenAppend("/public_html/RE2GpHd_1920x1080.jpg", Binary)

# GetFileSize("/public_html/RE2GpHd_1920x1080.jpg")
Command:  SIZE /public_html/RE2GpHd_1920x1080.jpg

# OpenPassiveDataStream(PASV, "APPE /public_html/RE2GpHd_1920x1080.jpg", 0)
Command:  PASV
Status:   Disposing FtpSocketStream...

```

**Comment by Mystogun** [comment] 2022-02-11 21:53
Hi @robinrodricks 

I also get a 0 size file on the server when using FileUpload, but the logs don't show me anything

Here are the logs:

```

# AutoConnect()

# AutoDetect(True, False)

# Connect()
Status:   Connecting to ***:21
Response: 220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
Response: 220-You are user number 7 of 50 allowed.
Response: 220-Local time is now 22:47. Server port: 21.
Response: 220-IPv6 connections are also welcome on this server.
Response: 220 You will be disconnected after 15 minutes of inactivity.
Status:   Detected FTP server: PureFTPd
Command:  AUTH TLS
Response: 234 AUTH TLS OK.
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.2803308.
Command:  USER ***
Response: 331 User *** OK. Password required
Command:  PASS ***
Response: 230 OK. Current restricted directory is /
Command:  PBSZ 0
Response: 200 PBSZ=0
Command:  PROT P
Response: 200 Data protection level set to "private"
Command:  FEAT
Response: 211-Extensions supported:
Response: EPRT
Response: IDLE
Response: MDTM
Response: SIZE
Response: MFMT
Response: REST STREAM
Response: MLST type*;size*;sizd*;modify*;UNIX.mode*;UNIX.uid*;UNIX.gid*;unique*;
Response: MLSD
Response: AUTH TLS
Response: PBSZ
Response: PROT
Response: UTF8
Response: ESTA
Response: PASV
Response: EPSV
Response: SPSV
Response: ESTP
Response: 211 End.
Status:   Text encoding: System.Text.UTF8Encoding+UTF8EncodingSealed
Command:  OPTS UTF8 ON
Response: 200 OK, UTF-8 enabled
Command:  SYST
Response: 215 UNIX Type: L8
Status:   Listing parser set to: Machine

# GetFilePermissions("/public_html")

# GetObjectInfo("/public_html", False)
Command:  MLST /public_html
Response: 250-Begin
Response: type=dir;sizd=4096;modify=20220211214012;UNIX.mode=0755;UNIX.uid=1003;UNIX.gid=99;unique=802gc42769; /public_html
Response: 250 End.

# UploadFile("RE2GpHd_1920x1080.jpg", "/public_html/RE2GpHd_1920x1080.jpg", Overwrite, False, None)

# FileExists("/public_html/RE2GpHd_1920x1080.jpg")
Command:  SIZE /public_html/RE2GpHd_1920x1080.jpg
Response: 213 0

# DeleteFile("/public_html/RE2GpHd_1920x1080.jpg")
Command:  DELE /public_html/RE2GpHd_1920x1080.jpg
Response: 250 Deleted /public_html/RE2GpHd_1920x1080.jpg

# OpenWrite("/public_html/RE2GpHd_1920x1080.jpg", Binary)

# GetFileSize("/public_html/RE2GpHd_1920x1080.jpg")
Command:  SIZE /public_html/RE2GpHd_1920x1080.jpg
Response: 550 Can't check for file existence
Command:  TYPE I
Response: 200 TYPE is now 8-bit binary

# OpenPassiveDataStream(PASV, "STOR /public_html/RE2GpHd_1920x1080.jpg", 0)
Command:  PASV
Response: 227 Entering Passive Mode (173,212,202,2,159,80)
Status:   Connecting to ***:40784
Command:  STOR /public_html/RE2GpHd_1920x1080.jpg
Response: 150 Accepted data connection
Status:   FTPS Authentication Successful
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.1919184.
Status:   Disposing FtpSocketStream...

# OpenAppend("/public_html/RE2GpHd_1920x1080.jpg", Binary)

# GetFileSize("/public_html/RE2GpHd_1920x1080.jpg")
Command:  SIZE /public_html/RE2GpHd_1920x1080.jpg

# OpenPassiveDataStream(PASV, "APPE /public_html/RE2GpHd_1920x1080.jpg", 0)
Command:  PASV
Status:   Disposing FtpSocketStream...

```
