### ISSUE TITLE
Failed to open file.

### ISSUE THREAD

**Issue by wernerbarnard** [robinrodricks/FluentFTP#195] opened 2017-09-22 11:59 UTC
Hi,

What would internally cause this error?

I am downloading +/- 10 files from FTP, all works fine - but 1 or 2 fails with this error.

This is my code:
```
using (var remoteFileStream = _ftpClient.OpenRead(remotePath, FtpDataType.Binary, true))
            {
                using (var newFileStream = File.Create(localPath))
                {
                    byte[] buffer = new byte[8 * 1024];
                    int len;

                    while ((len = remoteFileStream.Read(buffer, 0, buffer.Length)) > 0)
                    {
                        newFileStream.Write(buffer, 0, len);
                    }
                }
                
                _logger.LogInformation("GetReply");
                //response = _ftpClient.GetReply();

                //_logger.LogDebug($"Response.Success: {response.Success} | Code: {response.Code} | Error: {response.ErrorMessage}");
            }
```

GetReply is commented out, as it indefinitely "hangs" when I call that?

**Comment by artiomchi** [comment] 2017-09-26 07:07
Any specific reason you're using OpenRead instead of the Download methods that receive a destination file path as a parameter?

**Comment by wernerbarnard** [comment] 2017-09-26 07:18
Hi @artiomchi 

Yeah, it was the decision to use/do it that way due to the details in this issue: https://github.com/robinrodricks/FluentFTP/issues/143

**Comment by artiomchi** [comment] 2017-09-26 09:05
@wernerbarnard I just read through that issue - I think it may be related to #199 that was just recently fixed. Were you using .NET framework or .NET Core?

On top of that, I've noticed that enhanced active and passive mode don't work quite so well with some FTP servers. The reason FileZilla can work with them because it doesn't seem to use it, and instead uses regular passive mode.

Reading the files using a stream may have worked for some time, but ultimately it's a workaround around a deeper issue, and it would be better if we found out what it is and fixed it. Otherwise we'll keep getting various errors that are really hard to reproduce, since they're not easy to replicate.

What I would suggest is wait until the new build comes out (which should be soon), then try downloading the file using the regular file download method. If the issue persists, try switching to 
```c#
DataConnectionType = FtpDataConnectionType.PASV,
```

Please update us on whether that fixes the issue.

**Comment by wernerbarnard** [comment] 2017-09-26 10:51
Hi @artiomchi 

Cool, I'll do that when the new update comes out.

Yes - using .net core 2.0

Regarding PASV, my current working version is on:

```
DataConnectionType = FtpDataConnectionType.AutoPassive
```

Previously the listing only worked on Active, download on Passive, so I would change it in-between - but it's been quite inconsistent

**Comment by artiomchi** [comment] 2017-09-26 10:54
In my case, I've used it with a large number of FTP servers, and some of them didn't work on AutoActive or AutoPassive. I've currently switched all downloads either to use PORT for active or PASV for passive connections, and the ftp connections stopped dropping. That's in production now with the 8.0.2 release of FluentFTP, so you could try test the same with the current release :)

**Comment by wernerbarnard** [comment] 2017-09-26 10:56
Hi @artiomchi 

Yeah - i've tried all of the available options, will try again once i've updated

**Comment by robinrodricks** [comment] 2017-09-27 13:02
Can you try with the latest build : https://www.nuget.org/packages/FluentFTP/19.0.0

**Comment by wernerbarnard** [comment] 2017-09-29 12:19
Hi @robinrodricks 

I updated, and switched back to using the DownloadFile method, and removed all options (i.e. all default) - getting the original error again.

```
Failed to get the EPSV port from: 1342489 @    at FluentFTP.FtpClient.DownloadFileInternal(String remotePath, Stream outStream)
   at FluentFTP.FtpClient.DownloadFileToFile(String localPath, String remotePath, Boolean overwrite, FtpVerify verifyOptions)
```

Switching the download (using DownloadFile) to PORT gives this error:

```
Unexpected EOF for remote file /XXX.txt [0/1342489 bytes read] @    at FluentFTP.FtpClient.DownloadFileInternal(String remotePath, Stream outStream)
   at FluentFTP.FtpClient.DownloadFileToFile(String localPath, String remotePath, Boolean overwrite, FtpVerify verifyOptions)
```

**Comment by artiomchi** [comment] 2017-09-29 12:35
Hi @wernerbarnard 

Could you post the full ftp log from both attempts?

**Comment by wernerbarnard** [comment] 2017-09-29 23:23
Odd. I updated to 19.1 and default settings + DownloadFile worked now, I will run more tests and revert.

**Comment by robinrodricks** [comment] 2020-05-16 17:55
Closing as it seems to be fixed.

**Closed by robinrodricks** 2020-05-16 17:55 UTC
Labels: possible bug
