### ISSUE TITLE
FluentFTP!FtpSslLib.FtpSslStream.Dispose crash

### ISSUE THREAD

**Issue by dujianxin** [robinrodricks/FluentFTP#1111] opened 2022-12-19 03:21 UTC
**FTP Server OS:** Windows

**FTP Server Type:** Vsftpd / glFTPd / BFTPd / ProFTPD / Pure-FTPd / IBM CS FTP (z/OS, OS/400) / Windows CE / Windows Server IIS / Vax / VMS / OpenVMS / Tandem / HP NonStop

**Client Computer OS:** Windows

**FluentFTP Version:** 42.1.0

**Framework:** .NET 7

<write details about your bug report / feature request here>

**Logs :**

```

*******************************************************************************
*                                                                             *
*                        Exception Analysis                                   *
*                                                                             *
*******************************************************************************

*** WARNING: Unable to verify timestamp for PicFace64.dll
*** WARNING: Unable to verify timestamp for nvspcap64.dll
*** WARNING: Unable to verify timestamp for SogouPY.ime
*** WARNING: Unable to verify timestamp for SogouTSF.ime
*** WARNING: Unable to verify timestamp for nvwgf2umx_cfg.dll
*** WARNING: Unable to verify timestamp for nvldumdx.dll
*** WARNING: Unable to verify timestamp for nvd3dumx_cfg.dll
DEBUG_FLR_EXCEPTION_CODE(80131620) and the ".exr -1" ExceptionCode(e0434352) don't match
MethodDesc:   00007fff99596138
Method Name:          System.Net.Sockets.NetworkStream.WriteAsync(System.ReadOnlyMemory`1<Byte>, System.Threading.CancellationToken)
Class:                00007fff99584d70
MethodTable:          00007fff99596200
mdToken:              0000000006000161
Module:               00007fff98bc28a0
IsJitted:             yes
Current CodeAddr:     00007fff99c9d5d0
Version History:
  ILCodeVersion:      0000000000000000
  ReJIT ID:           0
  IL Addr:            00007ffff7c34e88
     CodeAddr:           00007fff99c9d5d0  (OptimizedTier1)
     NativeCodeVersion:  0000026B50271460
     CodeAddr:           00007ffff7c0f260  (ReadyToRun)
     NativeCodeVersion:  0000000000000000
Source file:  /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/NetworkStream.cs @ 625
MethodDesc:   00007fff99597610
Method Name:          System.Net.Sockets.Socket.SendAsync(System.Net.Sockets.SocketAsyncEventArgs, System.Threading.CancellationToken)
Class:                00007fff99584df0
MethodTable:          00007fff995985b8
mdToken:              0000000006000244
Module:               00007fff98bc28a0
IsJitted:             yes
Current CodeAddr:     00007fff99c9db00
Version History:
  ILCodeVersion:      0000000000000000
  ReJIT ID:           0
  IL Addr:            00007ffff7c38fa0
     CodeAddr:           00007fff99c9db00  (OptimizedTier1)
     NativeCodeVersion:  0000026B50271520
     CodeAddr:           00007ffff7c19490  (ReadyToRun)
     NativeCodeVersion:  0000000000000000
Source file:  /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs @ 2959
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range
Failed to request MethodData, not in JIT code range

KEY_VALUES_STRING: 1

    Key  : Analysis.CPU.mSec
    Value: 7359

    Key  : Analysis.DebugAnalysisManager
    Value: Create

    Key  : Analysis.Elapsed.mSec
    Value: 85462

    Key  : Analysis.IO.Other.Mb
    Value: 55

    Key  : Analysis.IO.Read.Mb
    Value: 1

    Key  : Analysis.IO.Write.Mb
    Value: 107

    Key  : Analysis.Init.CPU.mSec
    Value: 280

    Key  : Analysis.Init.Elapsed.mSec
    Value: 902376

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 541

    Key  : CLR.Engine
    Value: CORECLR

    Key  : CLR.Version
    Value: 7.0.22.51805

    Key  : Timeline.Process.Start.DeltaSec
    Value: 37

    Key  : WER.OS.Branch
    Value: vb_release

    Key  : WER.OS.Timestamp
    Value: 2019-12-06T14:06:00Z

    Key  : WER.OS.Version
    Value: 10.0.19041.1

    Key  : WER.Process.Version
    Value: 2.0.0.0


FILE_IN_CAB:  Pasteur.exe.12180.dmp

NTGLOBALFLAG:  0

PROCESS_BAM_CURRENT_THROTTLED: 0

PROCESS_BAM_PREVIOUS_THROTTLED: 0

APPLICATION_VERIFIER_FLAGS:  0

CONTEXT:  00000073548fc530 -- (.cxr 0x73548fc530)
rax=00007ffff7483011 rbx=0000000000000000 rcx=000080e815567985
rdx=0000000000000000 rsi=0000000000000002 rdi=0000000000000002
rip=0000022aad402178 rsp=00007ffff7461128 rbp=0000022aa7afdae8
 r8=00007fff98bfeba8  r9=0000000000000001 r10=00007fff98bfd4b8
r11=0000000000000001 r12=0000000000000001 r13=0000000000004000
r14=00007ffff7539d38 r15=0000022aa7a77d60
iopl=0         nv up di pl nz na pe nc
cs=ffff  ss=0000  ds=ffff  es=ffff  fs=ffff  gs=0000             efl=00000000
0000022a`ad402178 0860d5          or      byte ptr [rax-2Bh],ah ds:00007fff`f7482fe6=0f
Resetting default scope

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 00007ff834304f69 (KERNELBASE!RaiseException+0x0000000000000069)
   ExceptionCode: e0434352 (CLR exception)
  ExceptionFlags: 00000001
NumberParameters: 5
   Parameter[0]: ffffffff80131620
   Parameter[1]: 0000000000000000
   Parameter[2]: 0000000000000000
   Parameter[3]: 0000000000000000
   Parameter[4]: 00007ffff7410000

PROCESS_NAME:  Pasteur.exe

EXCEPTION_CODE_STR:  80131620

FAULTING_THREAD:  ffffffff

IP_ON_HEAP:  001572f2850fc085
The fault address in not in any loaded module, please check your build's rebase
log at <releasedir>\bin\build_logs\timebuild\ntrebase.log for module which may
contain the address if it were loaded.

FRAME_ONE_INVALID: 1

STACK_TEXT:  
00000073`548fa410 00007fff`99c9d84d System_Net_Sockets!System.Net.Sockets.NetworkStream.WriteAsync+0x27d
00000073`548fc980 00007fff`99c9dc22 System_Net_Sockets!System.Net.Sockets.Socket.SendAsync+0x122
00000073`548feee0 00007fff`99cac90e System_Private_CoreLib!System.ArgumentNullException.Throw+0x3e
00000073`548fef20 00007fff`99b1597a System_Private_CoreLib!System.Threading.ThreadPoolBoundHandle.AllocateNativeOverlapped+0xfa
00000073`548fef70 00007fff`99c9dd2a System_Net_Sockets!System.Net.Sockets.SocketAsyncEventArgs.DoOperationSendSingleBuffer+0xca
00000073`548ff040 00007fff`99c9dbaa System_Net_Sockets!System.Net.Sockets.Socket.SendAsync+0xaa
00000073`548ff090 00007fff`99c9da52 System_Net_Sockets!System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.SendAsyncForNetworkStream+0x22
00000073`548ff0e0 00007fff`99c9d724 System_Net_Sockets!System.Net.Sockets.NetworkStream.WriteAsync+0x154
00000073`548ff180 00007fff`e16d6638 System_Net_Security!System.Net.Security.SslStream.ShutdownAsync+0xa8
00000073`548ff1f0 00007fff`99b12d43 FluentFTP!FtpSslLib.FtpSslStream.Dispose+0x33
00000073`548ff250 00007fff`e16d8532 System_Net_Security!System.Net.Security.SslStream.Finalize+0x12


STACK_COMMAND:  ** Pseudo Context ** ManagedPseudo ** Value: ffffffff ** ; kb

SYMBOL_NAME:  System_Net_Sockets!System.Net.Sockets.NetworkStream.WriteAsync+27d

MODULE_NAME: System_Net_Sockets

IMAGE_NAME:  System.Net.Sockets.dll

FAILURE_BUCKET_ID:  CLR_EXCEPTION_80131620_System.Net.Sockets.dll!System.Net.Sockets.NetworkStream.WriteAsync

OS_VERSION:  10.0.19041.1

BUILDLAB_STR:  vb_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

IMAGE_VERSION:  7.0.22.51805

FAILURE_ID_HASH:  {7226f801-8111-10a7-66cf-5bace34cae0b}

Followup:     MachineOwner
---------



```

**Comment by timurposhva** [comment] 2022-12-19 10:24
What operating system was the code built on? In my case, it is reproduced when building the code on Debian host and it is not reproduced when building the code on Windows. I also found that the sizes of the assemblies are different. Haven't had time to figure out the difference yet.

**Comment by dujianxin** [comment] 2022-12-20 02:01
> What operating system was the code built on? In my case, it is reproduced when building the code on Debian host and it is not reproduced when building the code on Windows. I also found that the sizes of the assemblies are different. Haven't had time to figure out the difference yet.

I get FluentFTP package from [NuGet](https://www.nuget.org/packages/FluentFTP) and use it in my WPF application built on Windows. The size of the package is 387072 bytes.

**Comment by FanDjango** [comment] 2022-12-20 10:17
@dujianxin 

I just built a .NET 7.0 console application and ran some tests against an FTPS server. The code in `FtpSslLib.FtpSslStream.Dispose()`, which was called as expected (I was running in Debug / breakpoint set), did not fail or raise an exception.

So up to now, there is no information whatsoever beyond your dump to aid in debugging this. No real verbose FluentFTP log showing what happened up to the failure, no snippet of code showing **exactly** what you were doing when this failure occured, nothing. Just the dump.

So maybe you can think about how to continue this issue so it can move forward.

@timurposhva 

It would be helpful, if you are experiencing a similar but different problem, to open a separate issue and to provide the needed information to debug **your** problem. We can always bring the issues together if the problem actually turns out to be the **same**, but until then...

**Comment by robinrodricks** [comment] 2022-12-20 16:01
I am closing this because:

1. FanDjango has tested and verified our implementation works.

3. It appears to be a .NET framework issue (the bug is occuring in `System.Net.Sockets/src/System/Net/Sockets/NetworkStream.cs` which is out of scope)

5. The error is unmanaged (JIT level) so it is not our code, but the .NET framework which is failing

Thanks for testing @FanDjango.

**Closed by robinrodricks** 2022-12-20 16:01 UTC
Labels: possible bug
