### ISSUE TITLE
OpenReadAsync should not be deprecated

### ISSUE THREAD

**Issue by mjanulaitis** [robinrodricks/FluentFTP#851] opened 2022-02-26 17:20 UTC
I have created an interface to various providers such as Windows, SFTP and FTP/S.  The depreciation of OpenReadAsync means I have to one off when using FTPS.  Being able to open a stream then read line by line allows me to scan a portion of a file without having to pull the entire file, which in my case could be many GBs in size.  Please remove the deprecation so we can all read the stream on our own and decide on our own if we want to continue downloading after interrogating the first few chunks of data.

**Comment by robinrodricks** [comment] 2022-02-27 09:58
Possible duplicate of https://github.com/robinrodricks/FluentFTP/issues/841

Why does the deprecation hurt? Does it mess up your deployment pipeline?

**Comment by robinrodricks** [comment] 2022-02-27 09:58
It is not going to be deleted, but I want to discourage new users from using it.

**Comment by mjanulaitis** [comment] 2022-02-27 12:46
I understand the deprecation does not hurt and no it doesn't mess up my deployment pipeline but why discourage users from reading the stream on their own?  For me, interrogating the stream before reading the entire file is a valid use case.  I'm reading text log files and pulling just ten lines so the user can configure my software to read log entries of different types such as CSV, W3C, multi-line text log entries.  Does that make sense?

**Comment by robinrodricks** [comment] 2022-03-06 06:35
You are perfectly free to use it. As it is an advanced use case, if you can, you are welcome to.

However many new users pick up the library and start off using the Open* APIs and then report all kinds of nasty problems because they essentially start to rebuild DownloadFile/UploadFile on their own.

So this is the result of them being unaware that the Open* APIs are not a preferred API, and that high level APIs are available. This is why I have marked it deprecated.

**Comment by mjanulaitis** [comment] 2022-03-07 15:25
Copy that.  Thanks for the library.  It works great.

**Comment by robinrodricks** [comment] 2022-03-09 16:20
You are most welcome!

**Closed** 2022-03-09 16:20 UTC
Labels: question, faq, discussion

**Comment by lakeman** [comment] 2022-05-12 06:57
So people are expecting an api that solves #457? The problem of resuming ftp reads after some tcp failures?

Then perhaps that problem should be solved by providing an api with a fake stream instance. Allow the client to seek that stream, and only start a download on the first read operation. Moving any retry behaviour from the download file api.
