### ISSUE TITLE
OpenRead and Multithreading causes stale data prior to command execution

### ISSUE THREAD

**Issue by anandgmenon** [robinrodricks/FluentFTP#1324] opened 2023-09-07 09:32 UTC
**FTP Server OS:** Unix (Ubuntu 22.04)

**FTP Server Type:** Vsftpd

**Client Computer OS:** Windows

**FluentFTP Version:** 47.1.0

**Framework:** .NETCore 3.1

We are using the library in the azure logic apps FTP connector. One of customers reported an issue where we noticed the GetListing (in the asyncFTPClient) is returning an empty response. On checking the logs we see connection is getting stale somehow .We see these logs `Status:   Socket has stale data - prior to command execution` 
In some case it reconnects and gives a response after reconnecting but we notice some cases it returns empty response before reconnect. See logs below in both cases. We also see bunch of ` Testing connectivity using Socket.Poll()` regularly.

We have 2 questions here
- What could cause connections getting stale like we see below?
- In case of stale responses we see empty responses being sent in some cases, could that be a bug?

Unfortunately we were not able to reproduce this with same vsftpd config customer has. But we have a feeling this has something to do with their SSL settings as the issue seemed to never happen with SSL disabled.

Could you share some insights on this?

**Logs :**
Logs when empty response 

```
Status:   Testing connectivity using Socket.Poll()...
Status:   Testing connectivity using Socket.Poll()...
Status:   Testing connectivity using Socket.Poll()...
GetListing("/simulator/ftp/triggerCheck", Modify)
OpenDataStreamAsync("LIST /simulator/ftp/triggerCheck", 0)
OpenPassiveDataStreamAsync(AutoPassive, "LIST /simulator/ftp/triggerCheck", 0)
Status:   Socket has stale data - prior to command execution
```

Logs when it waits for reconnect

```

>         GetListing("/simulator/ftp/triggerCheck", Modify)
>         OpenDataStreamAsync("LIST /simulator/ftp/triggerCheck", 0)
>         OpenPassiveDataStreamAsync(AutoPassive, "LIST /simulator/ftp/triggerCheck", 0)
Status:   Socket has stale data - prior to command execution
Status:   The stale data was:
Stale:    226 Transfer complete.
Warning:  Reconnect needed due to stale data present on control connection (SslSessionLength: 38)
Status:   Command stashed: PASV
Status:   Closing/Disposing FtpSocketStream(control connection)
>         Connect(True)
Warning:  Reconnect (Count: 2)
Status:   FluentFTP 47.1.0.0(.NET Standard 2.1)
Status:   Connecting to IP #1= ***:21
Status:   Waiting for a response
Response: 220 (vsFTPd 3.0.5) [37.111m]
Status:   Detected FTP server: VsFTPd
Command:  AUTH TLS
Status:   Waiting for response to: AUTH TLS
Response: 234 Proceed with negotiation. [3ms]
Status:   FTPS authentication successful, lib = .NET SslStream, cipher suite = Tls12 (Aes256, 44550, 256) [5ms]
Command:  USER ***
Status:   Waiting for response to: USER ***
Response: 331 Please specify the password. [45ms]
Command:  PASS ***
Status:   Waiting for response to: PASS ***
Response: 230 Login successful. [50ms]
Command:  PBSZ 0
Status:   Waiting for response to: PBSZ 0
Response: 200 PBSZ set to 0. [2ms]
Command:  PROT P
Status:   Waiting for response to: PROT P
Response: 200 PROT now Private. [2ms]
Command:  FEAT
Status:   Waiting for response to: FEAT
Response: 211-Features:Response: EPRTResponse: EPSVResponse: MDTMResponse: PASVResponse: PBSZResponse: PROTResponse: REST STREAMResponse: SIZEResponse: TVFS
Response: 211 End [5ms]
Status:   Text encoding: System.Text.ASCIIEncoding+ASCIIEncodingSealed
Command:  SYST
Status:   Waiting for response to: SYST
Response: 215 UNIX Type: L8 [2ms]
Status:   Listing parser set to: Unix
Command:  TYPE I
Status:   Waiting for response to: TYPE I
Response: 200 Switching to Binary mode. [2ms]
>         SetWorkingDirectory("/")
Command:  CWD /
Status:   Waiting for response to: CWD /
Response: 250 Directory successfully changed. [2ms]
Command:  PWD
Status:   Waiting for response to: PWD
Response: 257 "/" is the current directory [2ms]
 
Status:   Executing stashed command
 
Command:  PASV
Status:   Waiting for response to: PASV
Response: 227 Entering Passive Mode (10,116,2,37,39,33). [4ms]
Status:   PASV advertised a non-routable IPAD. Using original connect dnsname/IPAD
Status:   Connecting to IP #1= ***:10017
Command:  LIST /simulator/ftp/triggerCheck
Status:   Waiting for response to: LIST /simulator/ftp/triggerCheck
Response: 150 Here comes the directory listing. [2ms]
Status:   FTPS authentication successful, lib = .NET SslStream, cipher suite = Tls12 (Aes256, 44550, 256) [3ms]
+---------------------------------------+
Listing:  -rw-r--r--    1 2001     2001        12288 Aug 15 13:26 .Data_triggerCheck.txt.swp
Listing:  -rw-rw-r--    1 2001     2001            6 Aug 10 17:33 0357.txt
-----------------------------------------
Status:   Closing/Disposing FtpSocketStream(data connection)
>         CloseDataStream()
Status:   Waiting for response to: LIST /simulator/ftp/triggerCheck
Response: 226 Directory send OK. [16ms]
Status:   Closing/Disposing FtpSocketStream(data connection)
Status:   Confirmed format Unix
>         GetModifiedTime("/simulator/ftp/triggerCheck/.Data_triggerCheck.txt.swp")
Command:  MDTM /simulator/ftp/triggerCheck/.Data_triggerCheck.txt.swp
Status:   Waiting for response to: MDTM /simulator/ftp/triggerCheck/.Data_triggerCheck.txt.swp
Response: 213 20230815132651 [2ms]
>         GetModifiedTime("/simulator/ftp/triggerCheck/0357.txt")
Command:  MDTM /simulator/ftp/triggerCheck/0357.txt
Status:   Waiting for response to: MDTM /simulator/ftp/triggerCheck/0357.txt
Response: 213 20230810173321 [2ms]
```

**Comment by FanDjango** [comment] 2023-09-07 20:24
Thank you for your report.

Redacted logs are always prone to causing unneeded QAs back and forth.

> What could cause connections getting stale like we see below?

You show the log, also the stale data.

```
GetListing("/simulator/ftp/triggerCheck", Modify)
OpenDataStreamAsync("LIST /simulator/ftp/triggerCheck", 0)
OpenPassiveDataStreamAsync(AutoPassive, "LIST /simulator/ftp/triggerCheck", 0)
Status:   Socket has stale data - prior to command execution
...
...
Status:   Socket has stale data - prior to command execution
Status:   The stale data was:
Stale:    226 Transfer complete.
```

So, a **previous** operation sent a `226 Transfer complete`, but it probably came too late and our internal logic had already considered the operation to have been finished (perhaps) before for some reason.

Sadly, I cannot see in your log excerpts what happened, since you have not included this. I would want to see the previous operation in its entirety in order to comment instead of invoking my crystal ball.

The "connection has not gone stale". What is meant is: "There is stale (=unexpected) data" on the connection that has never been picked up. In this specific case, where the stale data is a correct-looking FTP response, there are a number of possible reasons for this to happen (only one of them being a possible bug, by the way). Without the full log of this sequence, I cannot begin to analyze. **What happened prior to this `GetLisiting`?

> In some case it reconnects and gives a response after reconnecting but we notice some cases it returns empty response before reconnect. See logs below in both cases.

The log excerpts are not complete enough for me to fully understand what might be going wrong

> We also see bunch of  Testing connectivity using Socket.Poll() regularly

Time stamps in the log would be helpful to check if there is something going wrong with polling. You could turn off the polling if you suspect it is causing a problem. It is done to (try) to keep the connection allive (not always effective, IMO).

> In case of stale responses we see empty responses being sent in some cases

Need more complete logs, sorry.

A general comment:

The first problem is the one that causes the stale data.

All other observed problems are possible subsequent problems, where attempts to recover from the first problem are failing.

I would like to understand the first problem, that should be the first priority. **But:** I am also interested in finding out what parts of the retry logic are not working (i.e. Reconnecting and Re-Doing the command that failed due to stale data).

**Comment by anandgmenon** [comment] 2023-09-08 06:30
Thanks for the response, I am attaching the entrire logs [logs.txt](https://github.com/robinrodricks/FluentFTP/files/12556222/logs.txt) for like 15 mins, where the stale connection returning empty response has happened multiple times. First one is at 2023-09-07 05:58:24.7469825. The setup is like we do GetListing every 1 min. If we see the folder content is different from the previous, we also do OpenRead for a different file (That's why you'll see bunch of other operations other than GetListing). Also note that the logs will have output from multiple clients as we maintain a pool, where if we see a client is busy, we do create another client. Let me know if you need more details

**Comment by FanDjango** [comment] 2023-09-08 18:08
Ok, looks interesting. I understand what you are doing. This is going to be difficult.

I wonder if you could modify your logging very slightly to include some sort of client-id in each log line.

That would help diagnose a number of possible things that I can see, that are strange:

1. The socket polls seem to be increasing as time progresses. Could it be that also the number of open clients is increasing?
2. Are these connections all to the same server? How many simultaneous connections is it configured to actually accept?
3. It almost looks like the stale data was bona-fide data from a different client than the one that reported having stale data on his socket. Instantiating a new client should keep all things separate, especially on the socket level. But who knows, perhaps the parallelism is going wrong internally somewhere. But this is where a log with client id would really help.
4. Are you taking care that you do not bunch up a whole lot of GetListings if some of them take longer than a minute because of  timeouts or transfers taking that long in error cases? 

I see a number of places that look fishy, but with only the timestamps and no client id, it is nearly impossible to analyze.

Number 3 above would be my first suspicion.

**Comment by anandgmenon** [comment] 2023-09-09 09:02
Makes sense, I'll try to share the logs with client ids attached. Might take a couple of days as I have to get it from the customer

**Comment by anandgmenon** [comment] 2023-09-15 09:23
@FanDjango sorry for the late response, please find the logs with client ids attached here 
[logsWithId.txt](https://github.com/robinrodricks/FluentFTP/files/12617786/logsWithId.txt)
The important timestamps are 2023-09-14 05:52:13.5720266 where we see `Socket has stale data - prior to command execution` and empty response being send. But there are other occurences where Stale data error exists and we see it retries at 2023-09-14 05:33:04.1473279 for example

**Comment by FanDjango** [comment] 2023-09-15 19:54
I have a first question that comes up when I began to study your log, which is very impressive, thank you for that.

Do you use "`OpenRead(...0)`" in your code? It is designated obsolete (it is ony for internal use nowadays) and has a serious caveat if you use it in your code: **You must pick up the replay message _yourself_**, otherwise there is a (stale) message left on the socket? This might be the explanation for the "initial" error that is happening.

I would reccomend a recode to use "`Download....`" instead.

Meanwhile I am investigating the next possible problem with `GetObjectInfo(...)`.

I understand that the actual problem as seen by you is later and I will get to that.

**Comment by anandgmenon** [comment] 2023-09-18 04:11
@FanDjango one question here, in most cases I do see the clients before returning `Socket has stale data - prior to command execution` they also log ` Testing connectivity using Socket.Poll()`. What does that mean? Could it be that client is somehow reconnecting and we started an operation with that client before the reconnect was successful?

**Comment by FanDjango** [comment] 2023-09-18 11:06
@anandgmenon 
Actually, a socket poll is done whenever we internally decide to test the connection - to see if it is still connected, but only "once in a while".

The problem being: Because of the way TCP works, there is no real way to find out that the far side of the connection is still active, other than to "poll the socket". 

You do not want to do this too often, so as not to get a performance hit.

You can turn this feature off in the config, if you want to see if it causes any problems for you, or you can change the poll interval.

I must reiterate though: **Are you using `OpenRead(...)` in your code?** That is **definitely** the cause of stale data. All other errors after that are _subsequent_ errors that I must investigate.

**Comment by anandgmenon** [comment] 2023-09-18 11:19
> Are you using OpenRead(...) in your code?

Yes, we do. I'll try to replace it with DownloadStream in our code

**Comment by FanDjango** [comment] 2023-09-18 12:18
> Yes, we do. I'll try to replace it with DownloadStream in our code

That's good. Then I will need another log (with process IDs).

Meanwhile I have found one other (very small) bug. See #1334

**Comment by FanDjango** [comment] 2023-09-18 12:54
Look at this sequence, it shows the problem of the `OpenRead(...)`:

```
03.2238352	e79ed0 message: >         GetObjectInfo("/simulator/ftp/eai/send/KEN_ALL_ROME.json", False)
03.2239940	e79ed0 message: >         GetListing("/simulator/ftp/eai/send", Auto)
03.2241041	e79ed0 message: >         OpenDataStreamAsync("LIST /simulator/ftp/eai/send", 0)
03.2242161	e79ed0 message: >         OpenPassiveDataStreamAsync(AutoPassive, "LIST /simulator/ftp/eai/send", 0)
03.2243359	e79ed0 message: Command:  PASV
03.2244873	e79ed0 message: Status:   Waiting for response to: PASV
03.2454533	e79ed0 message: Response: 227 Entering Passive Mode (10,116,2,37,39,21). [20ms]
03.2455859	e79ed0 message: Status:   PASV advertised a non-routable IPAD. Using original connect dnsname/IPAD
03.2456856	e79ed0 message: Status:   Connecting to IP #1= ***:10005
03.2539420	e79ed0 message: Command:  LIST /simulator/ftp/eai/send
03.2541136	e79ed0 message: Status:   Waiting for response to: LIST /simulator/ftp/eai/send
03.2571451	e79ed0 message: Response: 150 Here comes the directory listing. [2ms]
03.2615699	e79ed0 message: Status:   FTPS authentication successful, lib = .NET SslStream, cipher suite = Tls12 (Aes256, 44550, 256) [4ms]
03.2617063	e79ed0 message: +---------------------------------------+
03.2658014	e79ed0 message: Listing:  -rw-rw-r--    1 2001     2001         2336 Jul 28 10:39 KEN_ALL_ROME.csv
03.2659050	e79ed0 message: Listing:  -rw-rw-r--    1 2001     2001         3844 Jul 28 10:40 KEN_ALL_ROME.json
03.2660008	e79ed0 message: Listing:  -rw-rw-r--    1 2001     2001         4750 Jul 28 10:41 KEN_ALL_ROME.xml
03.2660920	e79ed0 message: Listing:  -rw-rw-r--    1 2001     2001         4276 Jul 28 10:41 KEN_ALL_ROME.yaml
03.2661823	e79ed0 message: -----------------------------------------
03.2662734	e79ed0 message: Status:   Closing/Disposing FtpSocketStream(data connection)
03.2668223	e79ed0 message: >         CloseDataStream()
03.2669269	e79ed0 message: Status:   Waiting for response to: LIST /simulator/ftp/eai/send
03.2714197	e79ed0 message: Response: 226 Directory send OK. [17ms]
03.2715265	e79ed0 message: Status:   Closing/Disposing FtpSocketStream(data connection)

03.2718799	e79ed0 message: >         OpenRead("/simulator/ftp/eai/send/KEN_ALL_ROME.json", Binary, 0, 0)
03.2719804	e79ed0 message: >         GetFileSize("/simulator/ftp/eai/send/KEN_ALL_ROME.json", -1)
03.2721055	e79ed0 message: Command:  SIZE /simulator/ftp/eai/send/KEN_ALL_ROME.json
03.2722541	e79ed0 message: Status:   Waiting for response to: SIZE /simulator/ftp/eai/send/KEN_ALL_ROME.json
03.2738082	e79ed0 message: Response: 213 3844 [1ms]
03.2739297	e79ed0 message: >         OpenDataStreamAsync("RETR /simulator/ftp/eai/send/KEN_ALL_ROME.json", 0)
03.2740296	e79ed0 message: >         OpenPassiveDataStreamAsync(AutoPassive, "RETR /simulator/ftp/eai/send/KEN_ALL_ROME.json", 0)
03.2741408	e79ed0 message: Command:  PASV
03.2743707	e79ed0 message: Status:   Waiting for response to: PASV
03.2765932	e79ed0 message: Response: 227 Entering Passive Mode (10,116,2,37,39,18). [2ms]
03.2767221	e79ed0 message: Status:   PASV advertised a non-routable IPAD. Using original connect dnsname/IPAD
03.2768234	e79ed0 message: Status:   Connecting to IP #1= ***:10002
03.2854351	e79ed0 message: Command:  RETR /simulator/ftp/eai/send/KEN_ALL_ROME.json
03.2856041	e79ed0 message: Status:   Waiting for response to: RETR /simulator/ftp/eai/send/KEN_ALL_ROME.json
03.2880671	e79ed0 message: Response: 150 Opening BINARY mode data connection for /simulator/ftp/eai/send/KEN_ALL_ROME.json (3844 bytes). [2ms]
03.2918805	e79ed0 message: Status:   FTPS authentication successful, lib = .NET SslStream, cipher suite = Tls12 (Aes256, 44550, 256) [3ms]

03.3209301	e79ed0 message: >         GetObjectInfo("/simulator/ftp/eai/send/KEN_ALL_ROME.json", False)
03.3210532	e79ed0 message: >         GetListing("/simulator/ftp/eai/send", Auto)
03.3211916	e79ed0 message: >         OpenDataStreamAsync("LIST /simulator/ftp/eai/send", 0)
03.3213065	e79ed0 message: >         OpenPassiveDataStreamAsync(AutoPassive, "LIST /simulator/ftp/eai/send", 0)
03.3214287	e79ed0 message: Command:  PASV
03.3215897	e79ed0 message: Status:   Waiting for response to: PASV
03.3227036	e79ed0 message: Status:   Closing/Disposing FtpSocketStream(data connection)
03.3232984	e79ed0 message: Status:   Closing/Disposing FtpSocketStream(data connection)
03.3234027	e79ed0 message: Status:   Closing/Disposing FtpSocketStream(data connection)
03.3235749	e79ed0 message: Status:   Closing/Disposing FtpSocketStream(data connection)
03.3237327	e79ed0 message: Status:   Closing/Disposing FtpSocketStream(data connection)
03.3461942	e79ed0 message: Response: 226 Transfer complete. [24ms]

04.1468230	e79ed0 message: >         GetObjectInfo("/simulator/ftp/eai/send/KEN_ALL_ROME.json", False)
04.1469879	e79ed0 message: >         GetListing("/simulator/ftp/eai/send", Auto)
04.1470991	e79ed0 message: >         OpenDataStreamAsync("LIST /simulator/ftp/eai/send", 0)
04.1472140	e79ed0 message: >         OpenPassiveDataStreamAsync(AutoPassive, "LIST /simulator/ftp/eai/send", 0)
04.1473279	e79ed0 message: Status:   Socket has stale data - prior to command execution
04.1474849	e79ed0 message: Status:   The stale data was: 
04.1499974	e79ed0 message: Stale:    227 Entering Passive Mode (10,116,2,37,39,25).
04.1501068	e79ed0 message: Warning:  Reconnect needed due to stale data present on control connection 
```

In this graphic, I have marked the **first** failure:

![image](https://github.com/robinrodricks/FluentFTP/assets/51046875/40792e81-20bc-4bf4-bc81-c23ddd8ad53a)

You can see how the "226 Transfer complete" message is used for the response to the "PASV" command. This response was not picked up. *And* I must investigate why the "PASV" command simply accepted this. Let's call this "Mini-Bug #1".

The response to the "PASV" command was then stale data "227 Entering Passive Mode....." when doing the next command. This then caused a reconnect and more and more subsequent problems.

**Comment by anandgmenon** [comment] 2023-09-18 17:40
On refactoring the code using OpenRead(), I really don't think DownloadStream works for us actually. We use OpenRead to process large files (>1GB), which creates an ftp stream and pass it on to other functions which can process the stream (for example write it to blob). The same functionality I don't think is achievable by DownloadStream, where I would have to write it to a memory stream or any other other stream

**Comment by anandgmenon** [comment] 2023-09-19 03:06
@FanDjango please also take a look at these logs [logs2.txt](https://github.com/robinrodricks/FluentFTP/files/12655380/logs2.txt). These are logs for a particular client. If you see around 05:52:13.572, it is throwing the `stale data` and it doesn't tell what the stale data was like the previous cases and also it returns an empty response in this case (in the previous case it was retrying the stashed command). Also if you see the history this client, it doesn't do a OpenRead command at all. To me this looks like a different case than earlier, I would call it mini bug #2.

**Comment by FanDjango** [comment] 2023-09-19 07:42
Yes, I have seen that in the previous log. It is as if, once one thread gets stale data, all other threads also get stale data. One bad thread then corrupts all the others.

I am working this issue here at the moment and must take these things step by step.

Please stand by, as I am in the process of reproducing the problem(s) on my system here.

**Comment by FanDjango** [comment] 2023-09-19 08:46
Ok, I have merged a commit that will ignore the stale data caused by OpenRead. If you are able, please get the current master branch (it is not released to Nuget yet) and test with that one, so that mini bug #0 (!) is out of the way.

**Comment by FanDjango** [comment] 2023-09-19 08:54
Sorry, it doesn't completely work. I must make some more changes. Please wait...

**Comment by FanDjango** [comment] 2023-09-19 09:23
Ok. It is ready now.

**Comment by anandgmenon** [comment] 2023-09-19 10:15
I used the latest master and don't the stale data error when using OpenRead now. Would it be possible to generate a nuget for the latest version so we could ship to the customer as well to see if it solves all their issues?

**Comment by FanDjango** [comment] 2023-09-19 10:30
Not so fast. I am not finished yet. I'll tell you.

**Comment by FanDjango** [comment] 2023-09-19 12:26
Ok, I have merged the final changes.

I am not sure when we will have a Nuget release.

Now to the next steps:

Once you can get it to the customer, we can run it again and concentrate on errors still in the log.

**Comment by anandgmenon** [comment] 2023-09-19 14:06
Thanks, I'll wait for the Nuget release and then we can move forward with the next steps.

**Comment by FanDjango** [comment] 2023-09-19 19:18
Nuget Released!

**Comment by FanDjango** [comment] 2023-10-03 18:38
I suggest we close this issue and you could open a new issue (with logs and so on) for anything going wrong with the new release.

**Comment by anandgmenon** [comment] 2023-12-19 05:25
Hey @FanDjango, the customer finally came back to us. I think initially we suspected it to be an issue with `OpenRead()`. But we did make changes to add `GetReply(..)` in our code to prevent the stale data coming from OpenRead(..). Even though we see the stale data coming from OpenRead(..) does not exist anymore we still see the original issue still happening even if OpenRead(..) is not used.

```
await ftpClient.GetListing(path: folderPath, options: FtpListOption.Modify).ConfigureAwait(continueOnCapturedContext: false);
```
This is the only code we call in this scenario and from the [logs](https://github.com/robinrodricks/FluentFTP/files/13711497/ftp-logs.txt) we see stale data coming.

```
2023-12-19 01:35:06.8457893	ClientId: e5b70edb-f889-45c3-b233-3dc2980e931e Message: Status:   Testing connectivity using Socket.Poll()...
2023-12-19 01:35:06.8461810	ClientId: e5b70edb-f889-45c3-b233-3dc2980e931e Message: >         GetListing(""/simulator/ftp/triggerCheck"", Modify)"
2023-12-19 01:35:06.8463848	ClientId: e5b70edb-f889-45c3-b233-3dc2980e931e Message: >         OpenDataStreamAsync(""LIST /simulator/ftp/triggerCheck"", 0)"
2023-12-19 01:35:06.8466166	ClientId: e5b70edb-f889-45c3-b233-3dc2980e931e Message: >         OpenPassiveDataStreamAsync(AutoPassive, ""LIST /simulator/ftp/triggerCheck"", 0)"
2023-12-19 01:35:06.8469179	ClientId: e5b70edb-f889-45c3-b233-3dc2980e931e Message: Status:   Socket has stale data - prior to command execution
2023-12-19 01:35:28.2034362	ClientId: e5b70edb-f889-45c3-b233-3dc2980e931e Message: Status:   Testing connectivity using Socket.Poll()...
```
And the strange issue is after getting this error, it also returns and empty response to GetListing call instead of probably retrying or failing. Could you take a look at what might be going wrong here?

**Comment by FanDjango** [comment] 2023-12-19 09:55
Why is this still 47.1.0?
```
TIMESTAMP			message
2023-12-19 01:26:59.2746884	ClientId: e5b70edb-f889-45c3-b233-3dc2980e931e Message: >         Connect(False)
2023-12-19 01:26:59.2762367	ClientId: e5b70edb-f889-45c3-b233-3dc2980e931e Message: Status:   FluentFTP 47.1.0.0(.NET Standard 2.1)
2023-12-19 01:26:59.3198509	ClientId: e5b70edb-f889-45c3-b233-3dc2980e931e Message: Status:   Connecting to IP #1= ***:21
2023-12-19 01:26:59.3514669	ClientId: e5b70edb-f889-45c3-b233-3dc2980e931e Message: Status:   Waiting for a response
2023-12-19 01:26:59.3647528	ClientId: e5b70edb-f889-45c3-b233-3dc2980e931e Message: Response: 220 (vsFTPd 3.0.5) [738872.06d]
```

**Comment by anandgmenon** [comment] 2023-12-19 10:48
Here's the logs from 48.0.0 as well. See [logs](https://github.com/robinrodricks/FluentFTP/files/13714440/ftp-logs2.txt) . But I don't think there's anything different there.

>Are you repeatedly checking IsConnected? Then after 9 minutes the GetListing which fails due to stale data.

Yes, so internally we maintain a pool and every time there's a new request (in this case its every 1 minute), we check if the connctions in the pool are still connected.

I see the from the other issues there's a fix in progress. Do you want me to check with latest master and `IsStillConnected` to debug further?  (Not sure if I can work on it without a release but I can check)

**Comment by FanDjango** [comment] 2023-12-19 11:29
> Here's the logs from 48.0.0 

Sadly, 48.0.3 introduced some more logging. But never mind for now...

> Yes, so internally we maintain a pool and every time there's a new request (in this case its every 1 minute), we check if the connctions in the pool are still connected.

I thought so. And your setting of NoopInterval is less than 1 minute, so we get a poll every time you check. And you can see, the poll is not reliable to tell the disconnect. 

So yes, `IsStillConnected` would help you a lot, if you use it before doing any real stuff. And this would already be in current master.

> I see the from the other issues there's a fix in progress

Well, it's not reall a "**fix**". It is more some helpful additions and changes to make surviving a timeout, which takes down the control connection, easier. Not all servers and firewalls do this in the same fashion, thus there are so many possible symptoms.

> Do you want me to check with latest master and IsStillConnected to debug further? (Not sure if I can work on it without a release but I can check)

This depends on the level of pain you are currently experiencing. If using a non-released build is difficult but possible: the current master would suffice. You, in your code situation, would gain from DAEMON but only as the next step in this debugging process.

I am actually pretty sure that the (this) stale data is from take-downs. You might think that solving the timeouts would have made it unnecessary to add GetReplys to the OpenReads - but no: those places were **also** contributing to the problem. It's like fixing one, and then to have the next appear, like an onion.

**Comment by FanDjango** [comment] 2023-12-20 19:31
We should merge these two issues, #1385 and this one.

**Comment by anandgmenon** [comment] 2023-12-21 05:00
Yes, looks like same issue on different servers. I'm trying to get logs based on the latest version using `IsStillConnected()` for both the scenarios. But we can have one issue to track both

**Comment by anandgmenon** [comment] 2023-12-26 09:26
@FanDjango, sorry for the delay. Was waiting for customers to try out bits with latest master and `IsStillConnected()`.

Good news is the customer with the linux vsftpd server seems to have the issue resolved. We do not see any stale data in the logs anymore and the response of GetListing seems as expected. See 
[logs](https://github.com/robinrodricks/FluentFTP/files/13770321/logs.txt) in case you need them. 

However for IBM server mentioned in #1385, even though we don't see the stale data issue anymore, we somehow still see the _File must be specified by library/file.member_ error. But symptoms are different at different times though. See logs of one scenario 
[here](https://github.com/robinrodricks/FluentFTP/files/13770339/logs1.txt) and another one [here](https://github.com/robinrodricks/FluentFTP/files/13770343/logs2.txt).  I suspect maybe it is unrelated to the original issue with `IsConnected`. Could you take another look?

Also wondering if the implementation of `IsSupported` is complete, can we have a release for that? Also if the IBM server issue is unrelated we could reopen #1385 and close this issue after the release probably.

**Comment by robinrodricks** [comment] 2023-12-26 10:27
@anandgmenon  - All latest fixes/changes have been released - https://www.nuget.org/packages/FluentFTP

**Comment by FanDjango** [comment] 2023-12-26 10:42
```
2023-12-23 00:25:05.2828718	ClientId: 9aa0bd34-8d60-4702-8e64-02b5bcd4806c Message: Command:  RETR /E920/PY920/Export/Concur/list_p0087588bldj_20230327111206.txt
2023-12-23 00:25:05.2832895	ClientId: 9aa0bd34-8d60-4702-8e64-02b5bcd4806c Message: Status:   Waiting for response to: RETR /E920/PY920/Export/Concur/list_p0087588bldj_20230327111206.txt
2023-12-23 00:25:05.3262874	ClientId: 9aa0bd34-8d60-4702-8e64-02b5bcd4806c Message: Response: 501 File must be specified by library/file.member. [42ms]
```

```
2023-12-22 13:43:35.6646220	ClientId: c2d72102-196f-4a62-92b7-bf55c2b1d67c Message: Command:  LIST /E920/PY920/Export/Concur
2023-12-22 13:43:35.6648899	ClientId: c2d72102-196f-4a62-92b7-bf55c2b1d67c Message: Status:   Waiting for response to: LIST /E920/PY920/Export/Concur
2023-12-22 13:43:35.7074697	ClientId: c2d72102-196f-4a62-92b7-bf55c2b1d67c Message: Response: 501 File must be specified by library/file.member. [42ms]
```

@anandgmenon I think we can keep this one short and informal.

Please read our Wiki [on AS/400](https://github.com/robinrodricks/FluentFTP/wiki/IBM-zOS-and-OS-400-Support) and do a 
```
SITE NAMEFMT 1
```

**Comment by FanDjango** [comment] 2023-12-26 10:43
I wonder what you mean by "Also wondering if the implementation of IsSupported"? Typo?

**Comment by anandgmenon** [comment] 2023-12-26 11:09
Cool, that makes sense. I'll ask the customer to update that check again

**Comment by FanDjango** [comment] 2023-12-29 20:32
So, from the posts above I see:
> Good news is the customer with the linux vsftpd server seems to have the issue resolved. We do not see any stale data in the logs anymore and the response of GetListing seems as expected.

That means the newest version is looking good for this.

We will follow your other issues in #1385.

**Closed** 2023-12-29 20:33 UTC
Labels: fixed, vsftpd-server, released
