### ISSUE TITLE
AutoConnectAsync error: Timed out trying to read data from the socket stream!

### ISSUE THREAD

**Issue by Seabizkit** [robinrodricks/FluentFTP#825] opened 2022-01-14 13:23 UTC
busy trying to look at the source code to see if i can see why the below happens

```
Error	Failed Timed out trying to read data from the socket stream!
System.TimeoutException: Timed out trying to read data from the socket stream! 
 at FluentFTP.FtpSocketStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken token) 
 at FluentFTP.FtpSocketStream.ReadLineAsync(Encoding encoding, CancellationToken token) 
 at FluentFTP.FtpClient.GetReplyAsync(CancellationToken token) 
 at FluentFTP.FtpClient.HandshakeAsync(CancellationToken token) 
 at FluentFTP.FtpClient.ConnectAsync(CancellationToken token) 
 at FluentFTP.FtpClient.AutoDetectAsync(Boolean firstOnly, Boolean cloneConnection, CancellationToken token) 
 at FluentFTP.FtpClient.AutoDetectAsync(Boolean firstOnly, Boolean cloneConnection, CancellationToken token) 
 at FluentFTP.FtpClient.AutoConnectAsync(CancellationToken token) 
```

trying to see the source code for GetReplyAsync cant see it/ find it

**Comment by Seabizkit** [comment] 2022-01-14 13:50
this is with latest version 36.0.0

ok found it 

https://github.com/robinrodricks/FluentFTP/blob/d9d9945ce0c77f90408e06dfc4f009af4d879839/FluentFTP/Client/FtpClient_Stream.cs

which then goes to 
https://github.com/robinrodricks/FluentFTP/blob/d9d9945ce0c77f90408e06dfc4f009af4d879839/FluentFTP/Streams/FtpSocketStream.cs#L597

and well then that exception...

**Comment by Seabizkit** [comment] 2022-01-16 12:51
@robinrodricks 

defiantly something funky with the AsyncConnect...

![image](https://user-images.githubusercontent.com/1920090/149660463-a7f6e380-2353-4b19-8ef9-cd1a4a1eec0d.png)

it connects with normal Connect in about 35 secs.

but seems to hang... i increased the timeouts on the Async version as I get 

"Timed out trying to read data from the socket stream!" otherwise....

is there something you think im going incorrectly, PS if i use an ftp connection which connects faster... aka closer... 
then it connects.. but not with this client which takes like 40 secs

**Comment by Seabizkit** [comment] 2022-01-16 14:27
not sure who to debug this source code 
but one thing i can see is isnt 

```
while (await ReadAsync(buf, 0, buf.Length, token) > 0) {
				data.Add(buf[0]);
				if ((char) buf[0] == '\n') {
					line = encoding.GetString(data.ToArray()).Trim('\r', '\n');
					break;
				}
			}
```
meant to be , not the extra brackets
```
while ((await ReadAsync(buf, 0, buf.Length, token)) > 0) {
				data.Add(buf[0]);
				if ((char) buf[0] == '\n') {
					line = encoding.GetString(data.ToArray()).Trim('\r', '\n');
					break;
				}
			}
```

**Comment by Seabizkit** [comment] 2022-01-17 20:26
@robinrodricks  could you tell me what the intended why is to debug.. the source code... aka download source code, then add configuration manager ASYNC, problem i face when selecting this is i get all sorts of build issues, so not sure how im meant to get the config for ASYNC as the selected option, is there a guide setup?

**Comment by Seabizkit** [comment] 2022-01-19 06:39
ok i figure out most of it...

i was using AutoConnectAsync(ct) which then does thing i didnt expect but to be fair i should read more

anyway what ive found is by increasing timeouts you just prolong the one which would fail! as it tries more than 1, 
aka its going through all till it find 1 which works, it just so happens that the first 1 it tries is wrong and fails... cool.
at this point increasing the timeout just makes it look like its hanging.

leaving the timeout to 15 secs... it will then fail... **BUT** more coming

```
public override async Task<int> ReadAsync(byte[] buffer, int offset, int count, CancellationToken token) 
{
	if (BaseStream == null) {
		return 0;
	}

	m_lastActivity = DateTime.Now;
	using (var cts = CancellationTokenSource.CreateLinkedTokenSource(token)) 
	{
		cts.CancelAfter(ReadTimeout);
		cts.Token.Register(() => Close());
		try {
			var res = await BaseStream.ReadAsync(buffer, offset, count, cts.Token);

			// CTS for Cancellation triggered and caused the exception
			if (token.IsCancellationRequested)
			{
				throw new OperationCanceledException("Cancelled read from socket stream");
			}

			//CTS for Timeout triggered and caused the exception
			if (cts.IsCancellationRequested)
			{
				throw new TimeoutException("Timed out trying to read data from the socket stream!");
			}
			return res;
		}
		catch (Exception ex)
		{
			// Nothing of the above. So we rethrow the exception.
			throw;
		}
	}
}
```

if these lines are there...
```
if (token.IsCancellationRequested)
{
throw new OperationCanceledException("Cancelled read from socket stream");
}

//CTS for Timeout triggered and caused the exception
if (cts.IsCancellationRequested)
{
throw new TimeoutException("Timed out trying to read data from the socket stream!");
}
```

**then it does not try the next config getting's. and never get to the 1 which would work.**

aka just commenting these lines out make it then at least try the next auth and protocols, which then works perfectly

**Comment by robinrodricks** [comment] 2022-02-06 06:07
Can you try this and see if it works?

https://www.nuget.org/packages/FluentFTP/37.0.0

**Comment by Seabizkit** [comment] 2022-02-06 13:32
@robinrodricks  thx i tired the latest, at least there are no buld issues now, thx

now that I'm more familiar with the project i could check it faster...
In tests, see
![image](https://user-images.githubusercontent.com/1920090/152683085-82187d0e-8f1b-4bc4-8b16-7fbca3be6fb7.png)

No changes...
the strange thing is! that if u just Run this its passes, but if u debug it fails.

put a break point on this catch

![image](https://user-images.githubusercontent.com/1920090/152683220-5bc4f42b-e398-414b-97a8-1c35600bd4e5.png)

it should hit this more than once.... as the point of auto is that it should try each until it fails....

but on first catch it exists...

but what is amazing!!! is removing 

![image](https://user-images.githubusercontent.com/1920090/152683335-ba8e682d-4a35-4fa4-9a9e-60b87f79148b.png)

**makes it work**... you should be able to implement the correct logic with this information.

**Comment by Seabizkit** [comment] 2022-02-06 13:44
my guess is the timeout token is not reset when retrying.. next connection.. 
aka each attempt should have at least the default timeout 15 secs, my guess is that 
token.CandellationRequest is triggering... before it even has the time to go through the connections.

**Comment by Seabizkit** [comment] 2022-02-10 10:43
@jnyrup, project owner seems busy atm, could you confirm what I'm saying.

**Comment by Seabizkit** [comment] 2022-02-11 06:55
HI @jnyrup, thanks for looking sozs there is a lot going on before as i was trying to figure out what is going on....

What I'm saying is;
1. download, latest repo...
2 Run TestAutoConnectAsync **in debug**

does it pass....? **it fails for me** and does not do what I except when trying to follow the logic...aka it never loops over the other connection settings. 

but removing the throw inside the catch, then allows it to try the other connection settings which then allows it to pass...

**Comment by jnyrup** [comment] 2022-02-11 07:36
I tried running `TestAutoConnectAsync` _compiled_ in debug mode for the `net50` target framework and it passed.
I tried both with and without a debugger attached and it made no difference.

**Comment by jnyrup** [comment] 2022-02-11 09:33
I didn't set any break points.
Settings break points would increase the risk of a timeout, which from your initial stack trace seems to be the problems you're experiencing.

There are a plenty of reasons why a test could work on one machine but fail on another.
While deeply frustrating it's unfortunately not uncommon.
These tests makes a real internet connection, which makes them unstable.
E.g. if you turn off the WIFI while running the test will fail.

**Comment by FanDjango** [comment] 2022-02-11 22:59
@Seabizkit 

I would recommend closing this. The description "where is the implementation of GetReplyAsync" and the entire evolution of the documentation does not motivate well to understand the **actual** problem you are trying to solve.

Please reopen this as a new issue documenting what your real problem is, in a concise fashion.

Is the problem:

Connect does not work?
Connect does not work if in debug mode?
Test do not work?

I gave up after a while. Sometimes a fresh start will be the best way to succeed.

**Comment by jnyrup** [comment] 2022-02-12 12:03
I'm sorry, I don't follow what you're trying to say and I don't have the time to try to figure it out.
I agree with everything @FanDjango wrote above.
I can recommend reading https://stackoverflow.com/help/minimal-reproducible-example for tips on how write a good question.

If you haven't already read the documentation of this library, please see https://github.com/robinrodricks/FluentFTP/wiki#3-logging-and-troubleshooting

**Comment by Seabizkit** [comment] 2022-02-12 13:01
@FanDjango 

> Connect does not work?

**AutoConnectAsync** doesn't work 100% not even 50% of the time. 

> Connect does not work if in debug mode?
**AutoConnectAsync**
A little more complex to answer, sometime passes sometimes fails, 

> Test do not work?
test validates what I was experiencing in my own code. TestAutoConnectAsync has the same experience.

> I gave up after a while. Sometimes a fresh start will be the best way to succeed.
perhaps but was simple trying to try work through this massive lib.
I'm surprised that no 1 else is see the same results, needed some validation...
Honing down on what is happening.... giving details may help uncover what is happening, if i knew it would be easy and i wouldnt be here.

**Comment by FanDjango** [comment] 2022-02-12 15:26
Ok. Lets be systematic.

If **not** in debug mode, AutoConnectAsync fails **always**.

Questions:

Only for this one server, or for many servers or for all servers?

Does AutoConnect (not async) work? I am assuming: yes.

Can you put together a minimum piece of code that tries to autoconnect, post this here and also the log?

Then you posted:

> but what is amazing!!! is removing

and an [image](https://user-images.githubusercontent.com/1920090/152683335-ba8e682d-4a35-4fa4-9a9e-60b87f79148b.png)

> makes it work... you should be able to implement the correct logic with this information.

Question: Removing what? Are you saying: Removing the comments makes it work? Do you realize what that sounds like?

**Comment by robinrodricks** [comment] 2022-02-13 11:46
Afaik there is no difference in debug/release code, so the lib should have matching behavior regardless of build flags. Maybe just some .net exception handling is different in these modes, which may be triggering an edge case.

**Comment by robinrodricks** [comment] 2022-02-13 11:48
@FanDjango  and @jnyrup, firstly, thank you guys for responding on issues faced by other users, I appreciate it.

I agree with the both of you. The issue makes no sense to me either. 

@Seabizkit can you please confirm if AutoConnect works and the async API does not work. Is this the crux of your question?

**Comment by ScottyTarvan** [comment] 2022-07-28 05:46
In my case the problem is the async version of AutoConnect(), it does not honor the timeout settings. If I wrap the sync version into await Task.Factory.StartNew(client.AutoConnect) then the timeout values are honored.

**Comment by robinrodricks** [comment] 2022-07-28 13:32
> In my case the problem is the async version of AutoConnect(), it does not honor the timeout settings. If I wrap the sync version into await Task.Factory.StartNew(client.AutoConnect) then the timeout values are honored.

So please post this as a new issue. Random issues posted to existing threads are not observed.

**Comment by FanDjango** [comment] 2022-10-01 14:18
Closing this. Stale issue

**Closed by FanDjango** 2022-10-01 14:18 UTC
Labels: server specific

**Comment by FanDjango** [comment] 2025-01-07 22:44
@ScottyTarvan 

> In my case the problem is the async version of AutoConnect(), it does not honor the timeout settings. If I wrap the sync version into await Task.Factory.StartNew(client.AutoConnect) then the timeout values are honored.

Note this:
Setting timeouts on windows IS NOT SO EASY. Not our fault. Read this: https://github.com/robinrodricks/FluentFTP/wiki/FTP-Connection#faq_timeoutwindows
Async Client Timeout was not being honored (FluentFTP bug) but this has been fixed long ago (early this year, 2024?) you would need to search closed issues.
