### ISSUE TITLE
GetListing blocking with no timeout

### ISSUE THREAD

**Issue by helmerm** [robinrodricks/FluentFTP#262] opened 2018-01-05 10:32 UTC
**FTP OS:** ?? (https://www.drivehq.com/) 

**FTP Server:** ?? (https://www.drivehq.com/) 

**Computer OS:** Ubuntu 16.04 with Docker (Docker image: microsoft/dotnet:2.0-runtime) on Azure VM

My docker service randomly blocks on a GetListing call. There is no timeout, a restart of the service is required. 
I did not change any default settings. 
This has happened randomly several times within the last weeks.

Any possibility that some timeouts are not working as expected under .NET Core?

**Logs :**

Randomly the service blocks after sending the MLSD command and never receives the response.

```
sync_1           | 2018-01-04T18:27:20.556490347Z 17129314 [1] INFO FtpSyncProcess (null) - Listing CSV files
sync_1           | 2018-01-04T18:27:20.556493147Z
sync_1           | 2018-01-04T18:27:20.556495647Z # GetListing("/Data/Source_1", Auto)
sync_1           | 2018-01-04T18:27:20.556498447Z Command:  TYPE I
sync_1           | 2018-01-04T18:27:20.714983101Z Response: 200 Type set to I
sync_1           | 2018-01-04T18:27:20.715014201Z
sync_1           | 2018-01-04T18:27:20.715017301Z # OpenPassiveDataStream(AutoPassive, "MLSD /Data/Source_1", 0)
sync_1           | 2018-01-04T18:27:20.715020301Z Command:  EPSV
sync_1           | 2018-01-04T18:27:20.873663654Z Response: 501 Syntax error: Command not understood.
sync_1           | 2018-01-04T18:27:20.873687254Z
sync_1           | 2018-01-04T18:27:20.873689854Z # OpenPassiveDataStream(PASV, "MLSD /Data/Source_1", 0)
sync_1           | 2018-01-04T18:27:20.873692754Z Command:  PASV
sync_1           | 2018-01-04T18:27:21.031643009Z Response: 227 Entering Passive Mode (66,220,9,50,35,112).
sync_1           | 2018-01-04T18:27:21.031667409Z Status:   Connecting to 66.220.9.50:9072
sync_1           | 2018-01-04T18:27:21.189184163Z Command:  MLSD /Data/Source_1

```

Normally a Response is received.
```
sync_1           | 2018-01-05T10:15:44.040386500Z Response: 227 Entering Passive Mode (66,220,9,50,16,213).
sync_1           | 2018-01-05T10:15:44.040412000Z Status:   Connecting to 66.220.9.50:4309
sync_1           | 2018-01-05T10:15:44.197930265Z Command:  MLSD /Data/Source_1
sync_1           | 2018-01-05T10:15:44.363922522Z Response: 150 Connection accepted
```

**Comment by WolfspiritM** [comment] 2019-01-17 12:21
We currently are facing a similar issue. The problem is that when the server hangs and doesn't send back anything but keeps the session alive then there is no timeout for .NET Core!
The reason is that .NET Core uses the following way to make a Read on the socket:
https://github.com/robinrodricks/FluentFTP/blob/master/FluentFTP/Stream/FtpSocketStream.cs#L454

Not only is ".Result" a bad practice...but also does ReadAsync not trigger any timeout even so it's set on the socket. At least for the non async way it would be better to use
``` c#
return BaseStream.Read(buffer, offset, count);
```
instead.

For the Async I think the best solution would be to implement the timeout manually like that:

``` c#
		public override async Task<int> ReadAsync(byte[] buffer, int offset, int count, CancellationToken token) {
			if (BaseStream == null)
				return 0;

			m_lastActivity = DateTime.Now;
			var readTask = BaseStream.ReadAsync(buffer, offset, count, token);
			var timeoutTask = Task.Delay(m_readTimeout, token);
			var resultingTask = await Task.WhenAny(readTask, timeoutTask);
			if (resultingTask == timeoutTask)
			{
				Close();
				throw new TimeoutException("Timed out trying to read data from the socket stream!");
			}

			return readTask.Result;


		}
```

**Comment by mennowo** [comment] 2019-01-28 21:14
Hello, I am facing a similar issue here using .NET Core. Can you confirm the above to fix the issues? If so, it might be worth doing a PR with these changes? I will test the above in the next few days to see if it resolves the issues I am facing here. Greets, Menno

**Comment by WolfspiritM** [comment] 2019-01-29 12:56
@mennowo I will try to get a PR ready. For now I've fixed it outside of the FtpClient by wrapping the function calls I use like that. This way I can access and close the BaseStream until it's fixed in the main library:

``` c#
 public class WrappedFtpClient : FtpClient
 {
        public WrappedFtpClient(string host, int port, string user, string pass) : base(host, port, user, pass)
        {
        }

        public new Task DeleteFileAsync(string path)
        {
            return this.ExecuteWithTimeout(base.DeleteFileAsync(path), this.ReadTimeout);
        }

        public new Task<byte[]> DownloadAsync(string remotePath)
        {
            return this.ExecuteWithTimeout(base.DownloadAsync(remotePath), this.ReadTimeout);
        }


        // Workaround for a problem with Timeouts in FluentFTP
        private async Task ExecuteWithTimeout(Task task, int timeout)
        {
			var resultTask = await Task.WhenAny(task, Task.Delay(timeout));
			if (resultTask != task)
			{
				this.BaseStream.Close();
				throw new TimeoutException("Timeout");
			}
        }
        

        // Workaround for a problem with Timeouts in FluentFTP
        private async Task<T> ExecuteWithTimeout<T>(Task<T> task, int timeout)
        {
			var resultTask = await Task.WhenAny(task, Task.Delay(timeout));
			if (resultTask != task)
			{
				this.BaseStream.Close();
				throw new TimeoutException("Timeout");
			}

			return task.Result;
	}
}
```

**Comment by robinrodricks** [comment] 2019-01-29 13:45
@WolfspiritM This looks great. Great work debugging and finding a fix. Could you please explain in simple terms what is wrong with our current method of dealing with async calls?

**Comment by WolfspiritM** [comment] 2019-01-29 18:34
@robinrodricks Currently for .NET Core the synchronous call is using stream.ReadAsync() on the stream instead of the sync version stream.Read().
Async read calls (.ReadAsync or .BeginRead (which isn't available in .NET Core afaik)) on a stream will never use the ReadTimeout.
So if the server doesn't send anything back but keeps the connection alive FluentFTP is stuck on this call forever until the socket/stream closes.
For the sync version just using .Read instead will use the Timeout and doesn't need a call to .Result

In general using .Result is not the prefered way to call async code synchronously (which should be prevented cause of potential deadlocks anyway) cause it will for example not Unwrap Exceptions see:
https://stackoverflow.com/questions/17284517/is-task-result-the-same-as-getawaiter-getresult

The async part is a bit more complicated cause we should use the Async calls there.
There is a general issue with CancellationTokens in FluentFTP. The Async calls should pass a global CancellationToken down the line to the ReadAsync call.
Currently for the workaround I use another Task with Task.Delay and check if the timeout task is the first one that finished.
If it is the first one that finished, then I hardly close the stream. That will cause the "real" task to finish and causes it to get unstuck.

I've made an initial work to pass cancellation tokens from every method down to ReadAsync.
There are a few cases where this is not possible so I made a OnCancled function that checks for the cancelationtoken being triggered and then closing the stream/socket.
https://github.com/WolfspiritM/FluentFTP/commit/393a9202dbc2fbd0db825da693dfdaa4c2f9af15
It's a big change and I'm not sure if I got everything...but I think it's the cleanest way cause that's how ReadAsync is supposed to work.
I will take a look at it more later. I did change a few method invocations so the CancelationToken is in the end...so I don't think it's a good thing to include in a minor update.

``` c#
	// GetListing with Timeout of 1000 milliseconds
	var cts = new CancellationTokenSource(1000);
	var test = await cl.GetListingAsync(cts.Token);

	foreach (var item in test)
	{
		Console.WriteLine(item.FullName);
	}
```

The question is if we should combine that token with another one that is using ReadTimeout within the ReadAsync method so we are using the global ReadTimeout variable?!

**Comment by robinrodricks** [comment] 2019-01-31 04:14
Good find. That's some great work you've done. And yes, I've had comments before that our async implementation was shit. Apparently its just a wrapper around the sync methods instead of "true async". Not sure if a contributor fixed it along the way. Yes it will be a major update as the API has changed.

And yes we should definitely honor the ReadTimeout. Perhaps something like: (forgive my junk code, I don't have VS handy so this is just off the top of my head)

```csharp
if (token == null){
    token = new CancellationTokenSource(this.ReadTimeout);
}
if (token != null && token.timeout == null){
    token.timeout = this.ReadTimeout;
}
// and then pass token down the chain
```

**Comment by mennowo** [comment] 2019-01-31 14:05
Hey all, 
using the code in the previous posting from @WolfspiritM (that is, the first reply to the original issue) I see much better results so far. I am not currently using the async API.
Would be nice to see this make into the master branch, so I can switch back to using that instead of my own fork.
Thanks for the great work!
Greets, Menno

**Comment by robinrodricks** [comment] 2019-02-04 17:55
@WolfspiritM Any ETA on this? it sounds interesting..

**Comment by WolfspiritM** [comment] 2019-02-06 09:27
@robinrodricks I just commited some more changes including a "rewrite" to async for the hash algorithms: https://github.com/WolfspiritM/FluentFTP/commit/cf18f232ca6e2b97d0dbac31482a53d46d3e7a8f

I think I will open a pull request but it would be great if someone could give it a try before merging cause I didn't get much time to test it.

**Comment by robinrodricks** [comment] 2019-02-11 04:10
Yes it would be great if you can open a PR. Also, could you pull master into your branch and update it please?

**Comment by robinrodricks** [comment] 2019-02-21 06:55
Hi @WolfspiritM, any progress on this? it sounds like an interesting and useful improvement...

**Comment by WolfspiritM** [comment] 2019-02-21 12:55
Hi @robinrodricks I'm currently merging and fixing conflicts between master and my branch and noticed that master is not building. I've opened a review where that error got introduced. #372

**Comment by robinrodricks** [comment] 2019-02-21 13:43
Hi, could you fix that please? I'll accept your PR which will contain the
fix.

**Comment by robinrodricks** [comment] 2019-02-26 05:00
Hi @WolfspiritM Let me know when you make some progress with this... If you can do the proper async implementation for even one set of methods (ie UploadFile) I can repeat the same technique for the remaining...

**Comment by WolfspiritM** [comment] 2019-02-26 19:19
@robinrodricks I made a pull request. I'm not sure if that is the "proper" way to do it but as far as I could find it's the only way...ReadAsync just ignores the CancellationToken 😒

**Closed** 2019-02-27 05:04 UTC
Labels: bug, major, work in progress, workaround

**Comment by robinrodricks** [comment] 2019-02-27 05:43
Fixed by WolfSpiritM in release 23. Grab the nuget package here: [FluentFTP 23](https://www.nuget.org/packages/FluentFTP/23.0.0)
