### ISSUE TITLE
Unhandled exception when OpenSSL fails to connect due to Authentication failed.

### ISSUE THREAD

**Issue by PeterN** [robinrodricks/FluentFTP#1107] opened 2022-12-16 01:02 UTC
**FTP Server OS:** Unknown

**FTP Server Type:** Unknown

**Client Computer OS:** Debian

**FluentFTP Version:** 42.1.0

**Framework:** .NET 6

Just updated system from .netcore 3.1 to .net 6.0, and FluentFTP from 42.0.0 to 42.1.0, so I suspect this issue is triggered by the framework update rather than the FluentFTP update. However:

On trying to connect to the FTP server, OpenSSL is complaining that the SSL certificate is not trusted. This is actually correct, though it was working before.

However after failing to connect, it looks like an unhandled exception occurs (possibly in another thread or GC?), and this causes my process to be killed:

**Logs :**

I've not been able to get FluentFTP trace logs, however below is the exception that occurs.

```
[1       System.AggregateException: One or more errors occurred. (Authentication failed, see inner exception.)
[1        ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
[1        ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
[1        ---> Interop+Crypto+OpenSslCryptographicException: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
[1          --- End of inner exception stack trace ---
[1          at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]& sendBuf, Int32& sendCount)
[1          at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
[1          --- End of inner exception stack trace ---
[1          at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
[1          --- End of inner exception stack trace ---
[1          at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[1          at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
[1          at System.Threading.Tasks.Task.Wait()
[1          at FluentFTP.FtpSocketStream.ActivateEncryption(String targethost, X509CertificateCollection clientCerts, SslProtocols sslProtocols)
[1          at FluentFTP.FtpClient.Connect(Boolean reConnect)
[1          at FluentFTP.FtpClient.Connect()
```

Then a minute or two later:

```
[1 Unhandled exception. System.InvalidOperationException: This operation is only allowed using a successfully authenticated context.
[1    at System.Net.Security.SslStream.ThrowNotAuthenticated()
[1    at System.Net.Security.SslStream.ShutdownAsync()
[1    at FtpSslLib.FtpSslStream.Dispose(Boolean disposing)
[1    at System.Net.Security.SslStream.Finalize()
X.service: Main process exited, code=killed, status=6/ABRT
X.service: Failed with result 'signal'.
X.service: Service RestartSec=10s expired, scheduling restart.
```

**Comment by FanDjango** [comment] 2022-12-16 07:52
> Just updated system from .netcore 3.1 to .net 6.0, and FluentFTP from 42.0.0 to 42.1.0, so I suspect this issue is triggered by the framework update rather than the FluentFTP update.

It would be nice if you could confirm that by doing this with 42.0.0 (seems the easiest way to quickly check that statement).

That being said, I will check why the exception is not being caught. It is an `System.Security.Authentication.AuthenticationException` after all.

**Comment by PeterN** [comment] 2022-12-16 09:38
Thanks, I am now a bit more awake and have created a small test-case program, and I can confirm that 42.0.0 behaves the same.

I also tested targetting OS and framework versions: 
- Linux net5.0 also throws this exception
- Linux netcoreapp3.1 is able to connect to the server (despite the invalid certificate)
- Windows net6.0 is able to connect
- Windows netcoreapp3.1 is able to connect

To be honest I don't know why Windows is able to connect...

**Comment by FanDjango** [comment] 2022-12-16 09:48
I just checked:

```
#if NETSTANDARD
				catch (AggregateException ex) {
					if (ex.InnerException is IOException) {
						throw new AuthenticationException(ex.InnerException.Message);
					}
					throw;
				}
#endif
				catch (IOException ex) {
					if (ex.InnerException is Win32Exception { NativeErrorCode: 10053 }) {
						throw new FtpMissingSocketException(ex);
					}
#if NETFRAMEWORK
					throw new AuthenticationException(ex.Message);
#else
					throw;
#endif
```

I could add this new aggregate to that code, in addition to the IOExceptio. Would you be able to pick up a branch of mine if I try that?

**Comment by PeterN** [comment] 2022-12-16 09:57
Yes, I can try that -- I have just cloned and compiled master successfully so a branch should work.

**Comment by FanDjango** [comment] 2022-12-16 09:59
There you are: https://github.com/FanDjango/FluentFTP/tree/AuthExcept

It won't change much, it will still fail, but the exception will be reported in more standardised fashion (I hope).

**Comment by FanDjango** [comment] 2022-12-16 10:00
I wonder what is happening when you say, "after some minutes" you get the final failure. Too bad there is no log?

**Comment by PeterN** [comment] 2022-12-16 11:29
I think that is the FtpClient object being garbage collected later, though I'm not sure as a using() block didn't help.

With your change, the error is now:
```
Unhandled exception. System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
   at FluentFTP.FtpSocketStream.ActivateEncryption(String targethost, X509CertificateCollection clientCerts, SslProtocols sslProtocols)
   at FluentFTP.FtpClient.Connect(Boolean reConnect)
   at FluentFTP.FtpClient.Connect()
   at FtpsTest.Program.Main(String[] args) in I:\FtpsTest\Program.cs:line 35
```

Which looks a bit more contained. I'm not sure how to trigger the "after some minutes" part reliably yet.

The FtpSslStream::Dispose() dispose method is different between .NET Core 3.1 and .NET 6. It calls `base.ShutdownAsync()` in a try/finally block. Perhaps it needs to check the status of the base SslStream before calling that?

**Comment by FanDjango** [comment] 2022-12-16 11:42
Hmmm. I'm not happy with that, yet. 

Anyway:

SSL_ERROR_SSL
A non-recoverable, fatal error in the SSL library occurred, usually a protocol error. The OpenSSL error queue contains more information on the error. If this error occurs then no further I/O operations should be performed on the connection and SSL_shutdown() must not be called.

**Comment by PeterN** [comment] 2022-12-16 12:16
Re the SSL error, I did actually try to trust the FTP server's intermediate certificate (sourced from the CA) by including it in `/usr/share/ca-certificates`. While this does satisfy native openssl, curl, etc. it doesn't seem to help dotnet for some reason.

**Comment by FanDjango** [comment] 2022-12-16 12:21
Hmmm. You know that without a log, but in this case much more important - need a wireshark trace (client side is ok) to decode parts of the handshake at least, perhaps trace both the old and new and compare. I wonder what reasoning leads you to believe it is a certificate issue. I tend more to a protocol problem.

Re. the handling of the exception itself, I have put that on the back burner for now, as the original exception (although unhandled) gave the most information for now.

**Comment by PeterN** [comment] 2022-12-16 12:34
curl also fails to connect:

`curl: (60) SSL certificate problem: unable to get local issuer certificate`

I then manually installed the intermediate CA into my ca-certificates system (yes, bad idea in general...!)
Curl can now connect (although I've not provided credentials for the test):

`curl: (67) Access denied: 530`

**Comment by FanDjango** [comment] 2022-12-16 12:49
I see. Bit of a nightmare really.

This part is crazy:

> Linux net6.0 throws this exception 
Linux net5.0 also throws this exception
Linux netcoreapp3.1 is able to connect to the server (despite the invalid certificate)
Windows net6.0 is able to connect
Windows netcoreapp3.1 is able to connect

**Comment by FanDjango** [comment] 2022-12-20 20:58
How would you suggest that we can continue on this topic? Any suggestions?

**Comment by timurposhva** [comment] 2022-12-23 17:17
The program falls on the GC finalization step.
System_Net_Security!System.Net.Security.SslStream.ThrowNotAuthenticated()+0x46
System_Net_Security!System.Net.Security.SslStream.ShutdownAsync()+0xf3
FluentFTP.dll!Unknown+0x33
System_Net_Security!System.Net.Security.SslStream.Finalize()

This leads to a non-deterministic crash of the application.

**Comment by timurposhva** [comment] 2022-12-23 18:00
As a temporary solution can I suggest this
[MethodImpl(MethodImplOptions.NoOptimization)]

**Comment by FanDjango** [comment] 2022-12-23 21:36
@timurposhva I would appreciate it if you could elaborate a little on your input, which is much appreciated. Especially through what means you arrived at this.

**Comment by timurposhva** [comment] 2022-12-23 21:53
@FanDjango Sure. I determined that the problem is related to the JIT optimization. I’m currently working on identifying areas of code that are affected.

**Comment by FanDjango** [comment] 2022-12-23 21:59
Ok, I begin to understand.

What I don't understand but would like to learn:

You are able to reproduce this? Obviously Yes, I suppose.

You are doing this under Linux? Yes, I suppose.

How are you driving that far down? What tools, what method? Sorry, I am a noob to that area for now.

You advise (as a temp measure) to use `[MethodImpl(MethodImplOptions.NoOptimization)]`. Solely **around** the FtpSslStream Dispose override? We can do that, no problem.

**Comment by timurposhva** [comment] 2022-12-23 22:05
The error is reproduced on Windows and Linux. Net 5, 6, 7. On my servers, I have disabled optimization for the entire connection method (until I found a specific location). The error is reproduced only on one server.

**Comment by FanDjango** [comment] 2022-12-23 22:14
> is a consequence of another error

That is why I had been hoping for a verbose log of the sequence of evens leading up to the exception/failure

**Comment by timurposhva** [comment] 2022-12-23 22:18
If I disable optimization FtpSocketStream.ActivateEncryption error does not occur. This is what I'm trying to figure out

**Comment by robinrodricks** [comment] 2022-12-24 06:07
I think this has something to do with upstream .NET core because it is only occuring on Linux net6.0 and net5.0. 

I would suggest you can file this upstream? https://github.com/dotnet/core

**Comment by timurposhva** [comment] 2022-12-24 12:33
@robinrodricks @FanDjango 
According to this article https://learn.microsoft.com/en-us/dotnet/core/compatibility/cryptography/5.0/default-cipher-suites-for-tls-on-linux, starting from NET 5, the [SslStream](https://learn.microsoft.com/en-us/dotnet/api/system.net.security.sslstream) no longer works by default with old cipher suites.

But there is still a problem with skipping a Dispose method call(working on it now).

I also think it is necessary to safely call the method ShutdownAsync since it throws exceptions that terminate the application process.
https://learn.microsoft.com/en-us/dotnet/api/system.object.finalize?redirectedfrom=MSDN&view=net-7.0#System_Object_Finalize:~:text=If%20Finalize%20or,or%20destroy%20resources.

**Comment by FanDjango** [comment] 2022-12-24 12:47
@robinrodricks 

I already said that way upstairs.


> Hmmm. I'm not happy with that, yet.
> 
> Anyway:
> 
> SSL_ERROR_SSL A non-recoverable, fatal error in the SSL library occurred, usually a protocol error. The OpenSSL error queue contains more information on the error. If this error occurs then no further I/O operations should be performed on the connection and SSL_shutdown() must not be called.
> 
> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
> 
> OpenSslCryptographicException: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
> 
> Googling gets hits, so it is not unknown: https://stackoverflow.com/questions/66885550/interop-crypto-opensslcryptographicexception-error14094410ssl-routinesssl3-r
> 
> This one looks interesting, too: [dotnet/runtime#47117](https://github.com/dotnet/runtime/issues/47117)

**Cannot fix** is the one point, but I would still like to catch the failure correctly instead of having an unhandled exception.

**Somehow all participants are hesitant to show a verbose log**. Why? Especially since it is reproducible. Maybe all we need to do is modify our Dispose when the Authentication has **not** succeeded?

**Comment by timurposhva** [comment] 2022-12-24 13:18
> **Somehow all participants are hesitant to show a verbose log**. Why? Especially since it is reproducible. **Maybe all we need to do is modify our Dispose when the Authentication has **not** succeeded?**
This will solve the problem of finalization. But we need to figure out why the finalization is happening. Because the expected behavior when calling the Dispose method is to cancel the finalization.

**Comment by timurposhva** [comment] 2022-12-24 15:45
@FanDjango @robinrodricks 

1. Connect throws an exception (System.Security.Authentication.AuthenticationException)
2. Dispose(ShutdownAsync) throws an exception (System.InvalidOperationException). Object is not cleaned.
3. Finalize(ShutdownAsync) throws an exception (System.InvalidOperationException). Application process terminated.

The problem is related only to the method ShutdownAsync

**Comment by robinrodricks** [comment] 2022-12-26 08:05
@timurposhva  Ok, exceptions are being thrown. What is your suggested fix? That we catch this exception and throw a better one or just absorb it silently?

**Comment by timurposhva** [comment] 2022-12-26 08:20
> absorb it silently

It will be the best option since this exception is not fatal.

**Comment by timurposhva** [comment] 2023-01-01 06:39
`protected override void Dispose(bool disposing) {

			try {
#if NET5_0_OR_GREATER || NETSTANDARD2_1_OR_GREATER
				**base.ShutdownAsync()
					.ConfigureAwait(false)
					.GetAwaiter()
					.GetResult();**
#elif NETFRAMEWORK
				if (!_Closed) {
					_Closed = true;
					SslDirectCall.CloseNotify(this);
				}
#else
				;
#endif
			}
			finally {
				**if (!LeaveInnerStreamOpen) {
				base.Dispose(disposing);
				}**
			}
		}`

There are a few problems I’ve discovered:

1. `base.ShutdownAsync()` - should not be part of the resource clean-up process(https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1065). Must be controlled by client code.
2. `if (!LeaveInnerStreamOpen) `- `new FtpSslLib.FtpSslStream(GetBufferStream(), **true** `- as the internal stream is never automatically cleared then for SslStream cleaning never happens and `GC.SuppressFinalize` is never called. 

In my opinion the code should look like this
Remove `protected override void Dispose(bool disposing) `
Add new method

`protected void Close() {

#if NET5_0_OR_GREATER || NETSTANDARD2_1_OR_GREATER
				base.ShutdownAsync()
					.ConfigureAwait(false)
					.GetAwaiter()
					.GetResult();
#elif NETFRAMEWORK
				if (!_Closed) {
					_Closed = true;
					SslDirectCall.CloseNotify(this);
				}
#else
				;
#endif
		}`

**Comment by FanDjango** [comment] 2023-01-01 11:01
< re: `new FtpSslLib.FtpSslStream(GetBufferStream(), **true**,...`

Should we not say **false** instead?

**Comment by FanDjango** [comment] 2023-01-01 11:16
@PeterN I have made the changes suggested by @timurposhva and if you are able, you can try https://github.com/FanDjango/FluentFTP/tree/AuthExcept again, if you wish.

**Comment by timurposhva** [comment] 2023-01-01 12:58
> Should we not say **false** instead?

No. Buffer cleanup must be disposed by the calling code (`FtpSocketStream.Dispose`). `LeaveInnerStreamOpen=true` is a correct parameter.

**Comment by FanDjango** [comment] 2023-01-01 21:59
@timurposhva 

> No. Buffer cleanup must be disposed by the calling code (FtpSocketStream.Dispose). LeaveInnerStreamOpen=true is a correct parameter.

But actually we don't really want the inner stream left open. I know that we are closing all streams (buffer, sslstream and its base) and also disposing (if all code errors are fixed) by **our** own code. But then what is the purpose of that parameter if not to also close the inner stream **for us**?

**Comment by timurposhva** [comment] 2023-01-02 08:09
> But actually we don't really want the inner stream left open. I know that we are closing all streams (buffer, sslstream and its base) and also disposing (if all code errors are fixed) by **our** own code. But then what is the purpose of that parameter if not to also close the inner stream **for us**?

From a security point of view, this way you do not depend on the internal implementation of .NET. If a mistake is made in the .NET platform and the object stops being cleared, then you won’t even know about it without profiling. And it is considered good practice to clean up resources by the owners (If it's not a cache etc.).

**Comment by FanDjango** [comment] 2023-01-02 09:56
Ah so, I see. Thanks for explaining that to me. So that parameter is a bit of a "misdesign" by the .Net people - good practice is to **never** use that parm.

**Comment by timurposhva** [comment] 2023-01-02 10:20
> Ah so, I see. Thanks for explaining that to me. So that parameter is a bit of a "misdesign" by the .Net people - good practice is to **never** use that parm.

This is not entirely true. There are two use cases for this:

1. `LeaveInnerStreamOpen=true` When the calling code owns the stream and/or stream is a buffered stream. In this case, before disposing, you need to flush the buffer. Here the `SslStream` **borrows** the inner stream.
2.  `LeaveInnerStreamOpen=false` When the calling code does not own the stream then `SslStream` **owns** the inner stream and only `SslStream` can dispose inner since he is the only one who owns it.

**Comment by FanDjango** [comment] 2023-01-13 15:34
@IrishChieftain This is now released as V44

**Comment by timurposhva** [comment] 2023-01-20 11:02
> @PeterN Can we close this?

The unhandled exception is gone, but I got another problem:

Log:

# Connect(False)
Status:   FluentFTP 44.0.1.0
Status:   Connecting to IP #1= ***:990
Warning:  SSL Buffering force disabled, is .NET 5.0 and later
Status:   FTPS authentication successful, protocol = Tls12
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.0268872.
Status:   SslStream: Tls12 (Aes256, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, 44550, 256)
Status:   Waiting for a response
Response: 220-== Virtual Benefits Administrator SFTP Server -============================
Response: 220-== This is a private network.
Response: 220-== Unauthorized access and/or actions will result iin prosecution.
Response: 220 == For assistance, contact 262-946-1200. =============================== [738539.431d]
Command:  USER ***
Status:   Waiting for response to: USER ***
Response: 331 User ***, password please [25ms]
Command:  PASS ***
Status:   Waiting for response to: PASS ***

Problem:

The method `GetReplyAsyncInternal` enters an infinite loop.

```
            if (!exhaustNoop || elapsedMilliseconds <= (long) timeOut)
            {
              if (!exhaustNoop)
              {
                if (timeOut >= 0)
                {
                  // ISSUE: explicit non-virtual call
                  client.m_stream.ReadTimeout = __nonvirtual (client.Config).ReadTimeout;
                  // ISSUE: explicit non-virtual call
                  text = await client.m_stream.ReadLineAsync(__nonvirtual (client.Encoding), token);
                }
```
`await client.m_stream.ReadLineAsync(__nonvirtual (client.Encoding), token);` always returns null.

**Comment by FanDjango** [comment] 2023-01-20 11:13
Interesting: works for 
`Status:   Waiting for response to: USER ***`
but does not work for
`Status:   Waiting for response to: PASS ***`

Very strange?

**Comment by timurposhva** [comment] 2023-01-20 11:21
> Interesting: works for `Status: Waiting for response to: USER ***` but does not work for `Status: Waiting for response to: PASS ***`
> 
> Very strange?

The first few times the log looks like this:
# Connect(False)
Status:   FluentFTP 44.0.1.0
Status:   Connecting to IP #1= ***:990
Warning:  SSL Buffering force disabled, is .NET 5.0 and later
Status:   FTPS authentication successful, protocol = Tls12
Status:   Time to activate encryption: 0h 0m 0s.  Total Seconds: 0.0248618.
Status:   SslStream: Tls12 (Aes256, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, 44550, 256)
Status:   Waiting for a response
Response: 220-== Virtual Benefits Administrator SFTP Server -============================
Response: 220-== This is a private network.
Response: 220-== Unauthorized access and/or actions will result iin prosecution.
Response: 220 == For assistance, contact 262-946-1200. =============================== [738539.427d]
Command:  USER ***
Status:   Waiting for response to: USER ***
Response: 331 User ***, password please [23ms]
Command:  PASS ***
Status:   Waiting for response to: PASS ***
Response: 530 Not logged in. Username/password incorrect, user disabled, or user logged in too many times [3.02s]

# Dispose()
Status:   Disposing FtpClient object...
Status:   Closing/Disposing FtpSocketStream(control connection)

**Comment by FanDjango** [comment] 2023-01-20 11:49
Looks to me that ReadLineAsync is returning null instead of raising timeout. This needs to be looked into... Also looks to me like the server is ignoring you after some tries.

**Comment by FanDjango** [comment] 2023-01-20 11:54
This issue is far from the original and has three participants and four topics. You could have opened a new issue and perhaps referred to this one, you know. The OP is not responding to the original issue so I am going to close this. 

Please post your `The unhandled exception is gone, but I got another problem:` two comments into a new issue, can you do that?

**Comment by timurposhva** [comment] 2023-01-20 12:26
> Please post your The unhandled exception is gone, but I got another problem: two comments into a new issue, can you do that?

Sure

**Comment by robinrodricks** [comment] 2023-01-21 04:52
Closing as discussed.

**Closed** 2023-01-21 04:52 UTC
Labels: cantfix, response requested, upstream-bug, client-os-specific

**Comment by PeterN** [comment] 2023-01-27 11:48
Oh dear, apologies I did not see a notification on this.

I could not get a log as my testcase program did not crash in the same way, and I couldn't run the crashing code in production. However I will update to the new release and see what happens.

**Comment by PeterN** [comment] 2023-02-24 12:28
Finally able to confirm that the process does not terminate now, just a regular exception instead. 👍

**Comment by FanDjango** [comment] 2023-02-24 12:41
That's real nice of you! Thanks a lot - great news.
