### ISSUE TITLE
Message wording: Exception becoming a command? (GetReply timeouts)

### ISSUE THREAD

**Issue by Adhara3** [robinrodricks/FluentFTP#1209] opened 2023-02-23 09:52 UTC
**FTP Server OS:** Embedded

**FTP Server Type:**  Custom

**Client Computer OS:** Windows

**FluentFTP Version:** 45.0.4

**Framework:** FWK 4.8

This is not the firt time I see this happening, it's like an exception is swallowed and triggers some weird behavior.
`FtpLogger` is a Log4Net logger, I'm simply mapping FluentFTP logs into that.
```
02-23 09:32:18.881 INFO FtpLogger Response: 150 Opening BINARY mode data connection for myfile.bin. [3ms] 
02-23 09:32:21.959 DEBUG FtpLogger IOException 
02-23 09:32:21.959 DEBUG FtpLogger Waiting for response to: *IOException* 
```

A

**Comment by FanDjango** [comment] 2023-02-23 10:20
Perhaps that needs to be reworded to make it look better.

For us, however, this tells us:

The download terminated with an IOException. Some servers close the socket at the end of a download by **just closing the socket**. So, you get an IOException. But, it is normal behaviour, if afterward, you can receive a "226 Transfer successful" message. So we wait a short while for this message. And instead of doing that silently, we report that (verbose, mind you).

If your server is **not** such a (naughty) server, this message actually shows that your downloads are (you say you see it more than once) **failing** once in a while.  Perhaps they are then resumed / retried, I don't know.

> it's like an exception is swallowed

Well actually, the IO Exception **is being caught** and acted upon, depending on the situation.

>  triggers some weird behavior.

Not weird. See explanation above.

> `Waiting for response to: *IOException*`

We will improve the wording of this text.

But you could inverstigate more, under what circumstances IOException / failed downloads / automatically resumed downloads might be occurring without your knowledge?

**Comment by FanDjango** [comment] 2023-02-23 10:28
What is really meant is this:

```
02-23 09:32:21.959 DEBUG FtpLogger IOException in DownloadFileInternal
02-23 09:32:21.959 DEBUG FtpLogger Checking for response after: *IOException* 
```

**Comment by Adhara3** [comment] 2023-02-23 10:54
Ok I see with the rewording this souds better. However what if nothing is received after that? Is there a timeout for checking responses after IOException?

In this scenario the server was probably turned off so no clean connection management at all.

A

**Comment by FanDjango** [comment] 2023-02-23 11:01
It certainly **should** end with a timeout exception. If it does **not**, then this would be a bug.

The normal timeout situations seem to be handled correctly. 

Currently we are fighting a few edge cases where the socket does not close, socket poll does not update the status and READ returns null data. 

We have a branch out there that is being tested and correctly handles such edge cases  - it goes into a timeoutexception alright.

It is: https://github.com/FanDjango/FluentFTP/tree/Issue1156

**Comment by Adhara3** [comment] 2023-02-23 12:16
Maybe I was not clear on this, `02-23 09:32:21.959 DEBUG FtpLogger Waiting for response to: *IOException* ` was the last line in my logs. The thread was stuck there, never returned.

> Currently we are fighting a few edge cases where the socket does not close, socket poll does not update the status and READ returns null data.

I am afraid I am in one of those, my server is going up and down and sometimes it is simply killed leaving the connections without closing them (I am aware this is a shitty behavior, I apologize for this. I am a victim too!) 

Sorry if that was not clear.
A

**Comment by FanDjango** [comment] 2023-02-23 12:33
Use that branch and report back. We have identified the very probable place this is happening. The needed change is complex and it would be of great advantage if a user such as you could confirm it improves the situation.

**Comment by Adhara3** [comment] 2023-02-23 21:13
> Use that branch and report back. We have identified the very probable place this is happening. The needed change is complex and it would be of great advantage if a user such as you could confirm it improves the situation.

Hi,

I tested this branch with against the 45.0.4 in a parallel test and the improvement is dramatic. 
I got stuck with the 45.0.4 several times, while the app running with the new branch never got stuck once.  I will go in prod with this one, by the end of the weekend I will have even more test results.

Let's see what happens.

Thanks a lot
A

**Comment by robinrodricks** [comment] 2023-02-24 04:40
@FanDjango do you want to merge and release this fix branch of yours?

**Comment by FanDjango** [comment] 2023-02-24 09:44
Robin,

 

Yes. I am ready and it is merged. So by all means I would like a release.

 

Improve message wordings

 

EPSV & proxies: 

Ever since (some months ago) we have a DNS cache, where we store the SINGLE IPAD that we have successfully connected to, even if the server has multiple IP Addresses, we can rely on our own connect logic to pick up this same IPAD again on EPSV requests.

So therefore, the previous fix, by getting the IPAD from the socket endpoint, is no longer needed. Trouble was: On EPSV, this broke the proxy connect logic, where the proxy expects a DNS name and cannot make head not tail of the socket endpoint IP address.

 

GetReply: Improve TimeOut handling and lost connection handling

 

I added some tweaks to the NOOP logic as well, things I noticed when testing this new branch.

 

If you want to see something funny, here is another thing that I saw. It can't really happen in normal circumstances but during my testing I sort of provoked it to happen: Auto-Reconnect logic in Execute for command "QUIT" detects  stale data (I was testing crazy things) and decides to re-connect in order to successfully perform the QUIT command LOLOL:

 



 

mit freundlichen Grüßen,

Michael Stiemke ***@***.***)

 

AnSyNova GmbH

Ringstr. 13

85405 Nandlstadt

+49 8756 969 49 79
<http://www.ansynova.com <http://www.ansynova.com/> >

**Comment by FanDjango** [comment] 2023-02-24 09:46
@robinrodricks Yeah, a release seems in order. Sent you an email to help put together the release info. I know this is always a lot of work.

**Comment by FanDjango** [comment] 2023-02-24 09:48
@robinrodricks This is actually **not** server specific. We have another user with a totally different szenario experiencing the exact same problem. #1203

**Comment by FanDjango** [comment] 2023-02-24 09:52
@robinrodricks  @Adhara3 And this issue here is totally mixed up with issue #1156 as well. **I suggest close**. The original topic up at the top was about wording of some error messages, which has also been fixed and merged.

So fixing the wording of some messages is an enhancement in my mind and not a bug.

**Comment by robinrodricks** [comment] 2023-02-24 11:02
Released

https://www.nuget.org/packages/FluentFTP/45.2.0

Thanks a lot for fixing this fast @FanDjango

**Closed** 2023-02-27 08:44 UTC
Labels: enhancement, fixed
