### ISSUE TITLE
Chunk download

### ISSUE THREAD

**Issue by MohammadBMelhem** [robinrodricks/FluentFTP#1183] opened 2023-02-05 10:32 UTC
Hi, 
I need to download files from the sftp in chunks and avoid load all stream into the host memory 
, my case am reading many huge files 5GB each, if i will wait until get the whole file then will consume the memory and the application will break,
Is there is anyway to get the file in chunks and start process chunk by chunk

**Comment by FanDjango** [comment] 2023-02-15 21:33
This is very probably duplicate of #690 - cross index

**Comment by FanDjango** [comment] 2023-02-21 20:56
@MohammadBMelhem Follow #690 please.

**Closed by FanDjango** 2023-02-21 20:56 UTC
Labels: duplicate

**Comment by MohammadBMelhem** [comment] 2023-02-21 21:00
Thanks 😊
