### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by taoyouh** [robinrodricks/FluentFTP#187] opened 2017-09-14 08:29 UTC
ftp://202.120.39.248 works with FileZilla, Windows Explorer, and ftp command on Windows. But it doesn't work with FluentFTP (on both .Net Core 1.1 and UWP)
Error Message:

> {System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。(Did not response after some time. Connection failed.) 202.120.39.248:63390
>    at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
>    at System.Net.Sockets.SocketTaskExtensions.<>c.<ConnectAsync>b__3_1(IAsyncResult asyncResult)
>    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)}

StackTrace:

>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at FluentFTP.FtpSocketStream.Connect(String host, Int32 port, FtpIpVersion ipVersions)
>    at FluentFTP.FtpClient.OpenPassiveDataStream(FtpDataConnectionType type, String command, Int64 restart)
>    at FluentFTP.FtpClient.OpenDataStream(String command, Int64 restart)
>    at FluentFTP.FtpClient.GetListing(String path, FtpListOption options)
>    at FluentFTP.FtpClient.GetListing()
>    at ConsoleApp2.Program.Main(String[] args) in C:\Users\Zhaoquan\Documents\Visual Studio 2017\Projects\ConsoleApp2\ConsoleApp2\Program.cs:line 29

Code:
```
            FluentFTP.FtpClient conn = new FluentFTP.FtpClient();
            FluentFTP.FtpTrace.LogToConsole = true;
            conn.Host = "202.120.39.248";

            conn.Connect();

            var result = conn.GetListing();
```

**Comment by artiomchi** [comment] 2017-09-16 19:51
I've had some issues with a couple servers that I was connecting.. I believe those servers are at fault, but for all I know it could be an issue with FluentFTP.

The issue in my case was that FluentFTP will by default attempt to establish a EPSV connection, and will fall back to regular PASV if the server doesn't support it. The server in question reported that it supported EPSV, but connections to it timed out. Forcing a PASV connection solved it for us

```csharp
client.DataConnectionType = FtpDataConnectionType.PASV;
```

**Comment by hgupta9** [comment] 2017-09-21 17:59
If you are getting timeouts then try increasing all the timeout limits. This is needed for Azure too.

Thank you @artiomchi for filling in for me!

**Comment by hgupta9** [comment] 2017-09-21 18:00
And which is your server and OS?

**Comment by taoyouh** [comment] 2017-09-22 00:58
What @artiomchi said works. And it is not timout problem, because it takes 1 second for FileZilla to connect, but takes more than 30 seconds for my code to throw an ExtendedSocketException.
I tried both .NET Core 2.0 and UWP on Windows 10.0.15063.

**Comment by taoyouh** [comment] 2017-09-22 01:15
Fail version logging:

> # Connect()
> Status:   Connecting to 202.120.39.248:21
> Response: 220 Please visit http://sourceforge.net/projects/filezilla/
> Response: 220-FileZilla Server version 0.9.41 beta
> Response: 220-written by Tim Kosse (Tim.Kosse@gmx.de)
> Command:  USER anonymous
> Response: 331 Password required for anonymous
> Command:  PASS ***
> Response: 230 Logged on
> Command:  FEAT
> Response: 211 End
> Response: 211-Features:
> Response: MDTM
> Response: REST STREAM
> Response: SIZE
> Response: MLST type*;size*;modify*;
> Response: MLSD
> Response: UTF8
> Response: CLNT
> Response: MFMT
> Status:   Text encoding: System.Text.DBCSCodePageEncoding
> Command:  SYST
> Response: 215 UNIX emulated by FileZilla
> Status:   Auto-detected UNIX listing parser
> 
> # GetListing(null, Auto)
> 
> # GetWorkingDirectory()
> Command:  PWD
> Response: 257 "/" is current directory.
> Command:  TYPE I
> Response: 200 Type set to I
> 
> # OpenPassiveDataStream(AutoPassive, "MLSD /", 0)
> Command:  EPSV
> Response: 229 Entering Extended Passive Mode (|||57119|)
> Status:   Connecting to 202.120.39.248:57119

After Adding `client.DataConnectionType = FtpDataConnectionType.PASV;` 

> # Connect()
> Status:   Connecting to 202.120.39.248:21
> Response: 220 Please visit http://sourceforge.net/projects/filezilla/
> Response: 220-FileZilla Server version 0.9.41 beta
> Response: 220-written by Tim Kosse (Tim.Kosse@gmx.de)
> Command:  USER anonymous
> Response: 331 Password required for anonymous
> Command:  PASS ***
> Response: 230 Logged on
> Command:  FEAT
> Response: 211 End
> Response: 211-Features:
> Response: MDTM
> Response: REST STREAM
> Response: SIZE
> Response: MLST type*;size*;modify*;
> Response: MLSD
> Response: UTF8
> Response: CLNT
> Response: MFMT
> Status:   Text encoding: System.Text.UTF8Encoding
> Command:  OPTS UTF8 ON
> Response: 200 UTF8 mode enabled
> Command:  SYST
> Response: 215 UNIX emulated by FileZilla
> Status:   Auto-detected UNIX listing parser
> 
> # GetListing(null, Auto)
> 
> # GetWorkingDirectory()
> Command:  PWD
> Response: 257 "/" is current directory.
> Command:  TYPE I
> Response: 200 Type set to I
> 
> # OpenPassiveDataStream(PASV, "MLSD /", 0)
> Command:  PASV
> Response: 227 Entering Passive Mode (202,120,39,248,86,141)
> Status:   Connecting to 202.120.39.248:22157
> Command:  MLSD /
> Response: 150 Connection accepted
> +---------------------------------------+
> Listing:  type=dir;modify=20170921072734; 01  工程实践与科技创新[1] 2017-9-14
> Listing:  type=dir;modify=20170918051205; 02  工程实践与科技创新[2A] 2017-9-21updated
> Listing:  type=dir;modify=20170919070558; 03  工程实践与科技创新[3A]2017-9-20updated
> Listing:  type=dir;modify=20170920044313; 03  工程实践与科技创新[3A卓工]2017-9-19updated
> Listing:  type=dir;modify=20170911044710; 05  工程实践与科技创新[4A]当前未开课
> Listing:  type=dir;modify=20170516014714; 06  系统设计实践与创新[2]2017-5-19updated
> Listing:  type=dir;modify=20170921033506; 07  统计推断 课程设计2017-9-20updated
> Listing:  type=dir;modify=20170919110334; 08  工程问题建模与仿真
> Listing:  type=dir;modify=20170915065346; 09  通信基本电路实验2017-9-15updated
> Listing:  type=dir;modify=20150918102758; 10  通信原理实验
> Listing:  type=dir;modify=20170911114257; 11  智能系统设计
> Listing:  type=dir;modify=20170316083523; 12 《硬件描述语言与数字系统仿真》
> Listing:  type=dir;modify=20170601040101; 13 工程学导论
> Listing:  type=dir;modify=20170714034657; 14 2017全国大学生电子设计大赛集训
> Listing:  type=dir;modify=20150922043431; 。。。提示-推荐安装FileZillaClient作为下载客户端
> Listing:  type=dir;modify=20161018005408; 开放实验室管理和仪器技术资料 2016-10-18updated
> Listing:  type=dir;modify=20170508101909; 软件下载
> -----------------------------------------
> Status:   Disposing FtpSocketStream...

**Comment by taoyouh** [comment] 2017-09-22 01:20
Update. The server is actually UTF-8, but it seems irrelevant to this problem.
The is not a client-side bug, the problem is that the server don't receive EPSV connection. But maybe we should think of this "auto" behavior?

**Comment by robinrodricks** [comment] 2017-09-27 13:04
Can you try with the latest build : https://www.nuget.org/packages/FluentFTP/19.0.0

**Comment by taoyouh** [comment] 2017-09-29 12:09
@robinrodricks This version works the same. It works only when I use "client.DataConnectionType = FtpDataConnectionType.PASV". It still times out under default configurations.

**Comment by dallancarr** [comment] 2017-11-16 01:03
@robinrodricks So how does relate to reducing timeouts in relation to Azure Web Apps. It seems contradictory .

**Comment by robinrodricks** [comment] 2020-05-16 17:56
Closing as this seems to be server config related and not a bug in FluentFTP.

**Closed by robinrodricks** 2020-05-16 17:56 UTC
Labels: server specific, server-issue
