### ISSUE TITLE
Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by robinrodricks** [robinrodricks/FluentFTP#104] opened 2017-05-19 10:19 UTC
**NOTE FROM ADMIN:**

If you have this issue, please add your post below instead of creating duplicate issues!

First try this, it disables polling.

    client.SocketPollInterval = 0;

And try this, it reduces the polling interval to ensure that the connection does not time-out.

    client.SocketPollInterval = 1000;

Thanks.

----

Commonly occurs in:
- GetListing()
- DeleteDirectory()

For all the long running methods like UploadFileInternal and DowloadFileInternal and the above, we need to ensure that we poll the server to ensure its still connected. Could this be a fix to the "forcibly closed" error that we commonly receive?

**Comment by jblacker** [comment] 2017-05-19 12:56
I think I need to reread the spec, but can the connection close while data is being actively streamed to it though?

**Comment by hgupta9** [comment] 2017-05-19 15:14
@jblacker Good point. I created this "catch all" issue in case people were having trouble. I can't exactly explain or reproduce it. It just keeps coming up time and again so I assumed something was wrong with the methods. Also, I don't really know how/when Polling is done because it was written by JP Trosclair a long time ago.

**Comment by jblacker** [comment] 2017-05-19 15:23
Yeah the polling is happening on the Socket level deep in the weeds in `FtpSocketStream`, but determining exactly *when* it happens will take some serious debugging.  I noticed that whenever it does get called it it's always like 4 times in quick succession.

**Comment by hgupta9** [comment] 2017-05-19 15:26
Amazing info. The 4 times sounds like a bug - I think once is enough?

**Comment by jblacker** [comment] 2017-05-19 15:29
Yeah, I'd imagine once per interval would be enough.  You can clearly see it happening though in the log file posted in https://github.com/hgupta9/FluentFTP/issues/99#issuecomment-302676391

**Comment by Dunge** [comment] 2017-08-17 20:24
I'm using FluentFTP for the first time and having a similar issue.

My usage scenario is that every minutes it:
Connect, GetListing (return over 4000 items), Download 3 of these items, Disconnect.
There's no sleep or downtime or anything in between.
It fails more often than it succeed, but maybe once every 3 try it succeed.

The Connect always succeed, but either the GetListing or the Download throw me a System.Net.Sockets.SocketException (0x80004005)

I used FileZilla to test the ftp server and can connect/disconnect and download any files hundreds of times and never encountered any error, so I believe it's a problem in the lib and not the server.

[log.txt](https://github.com/hgupta9/FluentFTP/files/1232510/log.txt)

**Comment by Dunge** [comment] 2017-08-18 18:08
I ended up dropping FluentFTP and using System.Net.FtpWebRequest directly, and it works all the time.

**Comment by hung-doan** [comment] 2017-08-25 08:00
catch this error while uploading 1 file (1KB)

**Comment by jfbaudracco** [comment] 2017-09-03 08:46
I have the same problem.
I detect that the connection was closed every 137 files downloaded !

**Comment by jfbaudracco** [comment] 2017-09-03 10:37
After differents tests, it would seem there is a timeout on the data connection !
I tried to define DataConnectionTimeout propertie but no change.

**Comment by justindy** [comment] 2017-09-22 12:50
I've got this situation, too!!

My Test environment like this:
Framework: .Net Framework 4.0
FluentFTP : 18.02
Remote FTP Server: SunOS
Test Result :
    => [OK] Windows 7 Ent -> SunOS 
    => [OK] Windows 10 Home -> SunOS
    => [Failed] Windows Server 2012 -> SunOS

Architecture: x64

Help me~~~

**Comment by robinrodricks** [comment] 2019-06-08 11:58
Please try this:

> This means that on the server the [FTP daemon] service isn't running (probably not the case) or the service is currently still busy performing another operation. It almost sounds like the server is returning a message indicating it is still performing the last operation.

> Try reducing the polling interval to ensure that the connection does not time-out.

client.SocketPollInterval = 1000;

**Comment by omanThYp** [comment] 2020-05-22 02:05
Just in case there was any doubt this issue is still present.

For me, it is occurring after listing a bunch of directories, and downloading a bunch of files (hundreds) at very high speed.

It does not occur at lower network speeds.

It's actually predictable, and will occur on the same file every time if the remote directory contents remains unchanged.

I've also found that simply retrying the download causes the file contents to be incorrect. To work around, I've had add Disconnect() and Connect() before retrying.

I am really tempted to switch back to  the native .NET FTP support, except it doesn't support extended FTP functionality such as CHMOD.

**Comment by FanDjango** [comment] 2022-11-03 13:16
@oleksabor Using your exact github code and connecting to a very high performace proftpd server of my own, I can reproduce the issue.

### I am getting the same errors ( your sln is using FluentFTP V35).

After upgrading to FluentFTP V42 and making the few neccessary ->V40 migration changes, **the problem STILL can be reproduced**.

So now we can start to search for the problem.

**Comment by oleksabor** [comment] 2022-11-03 13:23
@FanDjango you have wrote your own ftp server!? Cool

 Sorry I enlisted to the army and can't assist you or test any fix if available.

**Comment by FanDjango** [comment] 2022-11-03 14:14
@oleksabor 
>very high performace proftpd server of my own

means, in my local network, on a (very) fast dedicated machine, linux, proftpd. Good for testing. Not wrote my own ;-)

**Comment by FanDjango** [comment] 2022-11-03 23:09
Some first results of testing, using @oleksabor initial approach as a basis. 

The goal was to find out a little bit more about the real problem and to remove conjecture.

1. I have modified the test program to **only** do the following (up to 500 times):

```
CWD /home/testuser
PWD
```

These commands **do not use** a data connection. No data connection (SSL) needs to be created and disposed. They only exercise the control connection.

These commands are iterated up to 500 times with no waits in between.

They always fail in the same way **on the 474th iteration**, on all of my available client systems.

2. The test suite will run all 500 iterations without failure if encryption is turned off.

3. The test suite encounters the _problem or multiple problems_ if encryption is turned on.

4. Disabling stream buffering does not help.

5. Disabling or enabling socket polling does not have any effect on the problem occurrence(s).

6. .NET 6.0 or .NET Framework 4.8 targets both exhibit the same problem(s).

7. Any problems occur after the same amount of iterations - deterministic and not random. Independent of host system.

8. The errors occur in `GetReply...ReadLine --> FtpSocketStream.ReadLine --> Read`. I put a try/catch into `FtpSocketStream.Read`: The errors themselves are **always**, (note: also in the original Getlisting/Download szenario) **"an attempt was made to access a socket in a way forbidden by its access permissions"**, an IOException, after which the socket is no longer connected, which is reacted to in different ways when they percolate upwards, depending on the function that you called. In a `GetListing()`, in a `Download...`, depending on the code that catches this exception, the further behaviour difffers. The control connection is closed though, which can cause a reconnect attempt, thus causing confusion if you don`t see that happening, or you can get "empty directories". Standardizing this behaviour could be a todo-item.

9. It looks like continuous reading from the SSL control connection stream in a huge amoung of single byte READ operations is somehow exhausting some resource inside the implementation of SslStream.

**Comment by FanDjango** [comment] 2022-11-04 11:14
So it seems that in this thread we are talking about **two sepearate issues**:

1. **Long running processes**, like a huge GetListing or a huge Download/Upload, getting terminated by the server suddenly shutting down the control connection.

2. **Strange errors** after performing **large amounts** of commands on the control connection

### Long running processes

That is the original post and its title corresponds to the error you would see: 
`Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host](https://github.com/robinrodricks/FluentFTP/issues/104#top)`

The following was mentioned in this issue, related to this issue:

a. Polling
b. NOOP commands

**Polling** is done whenever a FluentFTP method causes `IsConnected` to be queried (and of course, the last socket activity is longer ago than the polling interval). Polling ensures that our socket is kept "up-to-date" concerning its status, thus avoiding exceptions when trying to write to a closed socket. It does not cause a socket "to be kept alive if idle" and does not help for long running transfers on the data connection while the control connection is idle for a long time.

**NOOP** commands are actually the accepted way of keeping the control connection alive for long running transfers on the data connection.

This issue is actually fixed.

### Strange errors

After performing large amounts of `Read` operations on the SslStream socket, an `IOException` occurs with message `an attempt was made to access a socket in a way forbidden by its access permissions`

This is currently being investigated. See previous post.

I will open a separate issue for this problem. This issue here can be closed, the solution is to use NOOPs, see the [Wiki](https://github.com/robinrodricks/FluentFTP/wiki/Noop) for this.

**Closed** 2022-11-04 11:14 UTC
Labels: bug, work in progress, major
